### ISSUE TITLE
display scaling?

### ISSUE THREAD

**Issue by emhere** [hundredrabbits/Orca#10]
![image](https://user-images.githubusercontent.com/18672973/49976107-a05eea00-ff0e-11e8-961d-ea9762736828.png)

it's very difficult to read at 4k resolution on my monitor, and while I can change the monitor resolution to resolve this issue on my end, it would be far more convenient to just have some options for display scaling, if possible

**Comment by neauoire** [comment]
Oh my god, hahahaha.
Okay, yes. I will add a zoom option.

**Comment by neauoire** [comment]
- `ctrl/cmd+=` Zoom In.
- `ctrl/cmd+-` Zoom Out.
- `ctrl/cmd+0` Zoom Reset.
