### ISSUE TITLE
In the readme, M says multiply, but it should say modulo

### ISSUE THREAD

**Issue by destroyboy** [hundredrabbits/Orca#100]
The readme should be updated.

**Comment by neauoire** [comment]
`M` is the **multiply operator**.
It multiplies the two ports together, you might have an old version of Orca, try updating if you're still seeing the modulo operator.

**Comment by destroyboy** [comment]
@neauoire ah great, thanks, I should probably build it myself but I didn't have the right version of node, I might try again.

**Comment by neauoire** [comment]
If you want to have Orca updated automatically, download it through the itch.io client, it'll handle updates for you.

**Comment by destroyboy** [comment]
Thanks. I'll try that out.
