### ISSUE TITLE
key : on Azerty keyboard launches / to find

### ISSUE THREAD

**Issue by nlebellier** [hundredrabbits/Orca#110]
Hi,

Congratulations for this software and your work.

I use the latest version via a gentle git pull.

i meet this issue on every azerty keyboard (windows 10 or Ubuntu 18.04.02), when i type on the `:` key, Orca reacts as y type on the `/` character which is on a azerty keyboard the same key.
it's annoying to play just a little midi note.

![image](https://user-images.githubusercontent.com/4880966/57965307-d59ab880-7942-11e9-9a77-aa2c66bc5c60.png)

An idea ?
Thanks

**Comment by neauoire** [comment]
Just pushed an update that should fix that :)

**Comment by nlebellier** [comment]
Perfect ! Merci for french users !
