### ISSUE TITLE
Welcome screen put the letters command in CAPS

### ISSUE THREAD

**Issue by nlebellier** [hundredrabbits/Orca#111]
Just a point of view : it's a good idea to have a main view of all commands but it's odd to put them in lowercase because as you know your commands are case sensitive. Why don't you put then in Uppercase but as comments ?

Cheers

**Comment by neauoire** [comment]
Mhmm, I could make them uppercase, but I don't think it matters too much, lowercase or uppercase is equally important. Do you know how to use letters in lowercase?

**Comment by nlebellier** [comment]
[image: image.png]
Well there is a difference lowercase or uppercase letter ? Right ?

if i type an a or an A the result is not the same ?
I understand uppercase are for commands and lowercase for in midi notes c >
c sharp
May i miss something ?

---
NLB

**Comment by neauoire** [comment]
AAAh yes, no they are both operators! Lowercase require a bang to operate.

Have a look at this:

```
.D..
..H.
.xS.
```

**Comment by nlebellier** [comment]
ok indeed ! thanks to your example i get it ! 

Another a little question : to play with sample, which sampler i can use, i try estra but it fails to load the samples. Do you know an sampler working with osc protocol ?

**Comment by neauoire** [comment]
You should try just using Ableton? Or maybe even Supercollider/SonicPi if you just want to load samples.
