### ISSUE TITLE
transpose.js file Catch b

### ISSUE THREAD

**Issue by nobodycarestrue** [hundredrabbits/Orca#115]
In the transpose.js file, I think the Catch B section should all be shifted one octave up, like this? It makes more sense to go up 1 on these notes instead of going down 11 (a whole octave).

```
  // Catch b
  'b': 'C1',
  'i': 'C1',
  'p': 'C2',
  'w': 'C3'
```

Also, while here, is there a reason we need to have 4 redundant notes? (A,a,B,b) = (H,h, I, i)

**Comment by nobodycarestrue** [comment]
If we could do something like the following, we can get 3 extra notes with a note range of C0-g3 (right now it's C0-F3).

```
'use strict'

export default {
  'A': 'A0',
  'a': 'a0',
  'B': 'B0',
  'C': 'C0',
  'c': 'c0',
  'D': 'D0',
  'd': 'd0',
  'E': 'E0',
  'F': 'F0',
  'f': 'f0',
  'G': 'G0',
  'g': 'g0',
  'H': 'C1',
  'h': 'c1',
  'I': 'D1',
  'i': 'd1',
  'J': 'E1',
  'K': 'F1',
  'k': 'f1',
  'L': 'G1',
  'l': 'g1',
  'M': 'A1',
  'm': 'a1',
  'N': 'B1',
  'O': 'C2',
  'o': 'c2',
  'P': 'D2',
  'p': 'd2',
  'Q': 'E2',
  'R': 'F2',
  'r': 'f2',
  'S': 'G2',
  's': 'g2',
  'T': 'A2',
  't': 'a2',
  'U': 'B2',
  'V': 'C3',
  'v': 'c3',
  'W': 'D3',
  'w': 'd3',
  'X': 'E3',
  'Y': 'F3',
  'y': 'f3',
  'Z': 'G3',
  'z': 'g3',
  // Catch e
  'e': 'F0',
  'j': 'F1',
  'q': 'F2',
  'x': 'F3',
  // Catch b
  'b': 'C1',
  'n': 'C2',
  'u': 'C3'
}

```

**Comment by neauoire** [comment]
The reason for the redundancy is easy to understand with this little program

```
...D4H
D4..iZ
.:03C0
```

**Comment by nobodycarestrue** [comment]
I understand that you're going for something like this:
<img width="1160" alt="Scale-A1" src="https://user-images.githubusercontent.com/47595933/58069876-caff3f80-7b4b-11e9-89f9-e4f6be586ba1.png">

But doesn't this make more sense musically?
<img width="1160" alt="Scale-B1" src="https://user-images.githubusercontent.com/47595933/58069896-e0746980-7b4b-11e9-8d87-afb71e91ceb0.png">

Especially when one uses a `T` or something. As is now, this is the result:
<img width="1383" alt="Scale-A2" src="https://user-images.githubusercontent.com/47595933/58069918-fb46de00-7b4b-11e9-9f21-b6e4669981ce.png">

would this not be better?
<img width="1412" alt="Scale-B2" src="https://user-images.githubusercontent.com/47595933/58069952-16b1e900-7b4c-11e9-8f95-5f211b4b346c.png">

**Comment by neauoire** [comment]
You are absolutely right, I hadn't seen it that way. 
I will correct this 👍

**Comment by nobodycarestrue** [comment]
Very cool. Hope all's been well. 🐳

**Comment by neauoire** [comment]
<img width="1092" alt="Screen Shot 2019-05-21 at 6 23 27 AM" src="https://user-images.githubusercontent.com/1455726/58070436-f8221100-7b90-11e9-94d4-a7b7c0bd2a11.png">

It has been crazy exhausting, but very inspiring, I'm looking forward to return to the boat in our isolated place in Japan tomorrow.

**Comment by nobodycarestrue** [comment]
I can imagine, but super awesome. Out there spreading the good Orca word. Wish you safe travels.
