### ISSUE TITLE
Can't select with shift and left key

### ISSUE THREAD

**Issue by nlebellier** [hundredrabbits/Orca#117]

**Comment by nlebellier** [comment]
hi,

Just git pull the sources and i can't select in left direction ? Odd no ?

**Comment by neauoire** [comment]
Yeah the cursor is a bit limited, I haven't gotten around to implementing negative scaling.

**Comment by sixclones** [comment]
Happy to see this feature added!

**Comment by neauoire** [comment]
Fixed with #177
