### ISSUE TITLE
We need to click on zone command to type command

### ISSUE THREAD

**Issue by nlebellier** [hundredrabbits/Orca#123]
hi,

When we toggle to commander mode, it would be great to be able to yype the commands without clicking in the zone with the mouse before ?

No ?

**Comment by neauoire** [comment]
clicking in the zone? what does that mean? If you press `cmd+k`, you should be able to type right away :)

**Comment by nlebellier** [comment]
oh yes if we use the keyboard shortcuts but if we use the menu item it doen't work.

**Comment by neauoire** [comment]
If I click on the menu option, `view > toggle commander`, I am able to type right away on `OSX 10.6.2`. Cannot reproduce.

I recommend using `ctrl+k` in the meantime, until someone who can reproduce, and make a PR, can fix this.

**Comment by nlebellier** [comment]
i got --- blinking into the "command zone" on ubuntu 19.04 and windows 10. but the ctrl + k is better

**Comment by neauoire** [comment]
✊
