### ISSUE TITLE
OSC port to be constant

### ISSUE THREAD

**Issue by nlebellier** [hundredrabbits/Orca#124]
Hi,

The port used by Orca to send osc information is not constant. Isn't it ?

![image](https://user-images.githubusercontent.com/4880966/58716873-483b7780-83ca-11e9-99f7-f36212c73d55.png)

A bit boring if we want to communicate with others program we have to change the port into code.
May i miss something ? :-)

**Comment by neauoire** [comment]
In what case do you need the sender's port to be constant?

**Comment by nlebellier** [comment]
with communicate with sonic pi as example
https://in-thread.sonic-pi.net/t/using-orca-to-control-sonic-pi-with-osc/2381/11

**Comment by neauoire** [comment]
The port to which orca sends does not change, if you select `osc > Sonic Pi`, every sent message with be routed to that address. The port from which it is sent might change, but does not impact this scenario.

**Comment by nlebellier** [comment]
So we agree it's annoying to have to change this port value in Sonic Pi code each time we launch Orca...

So my question was  can we set the port from which orca sends its messages to be constant ?
Cheers

**Comment by neauoire** [comment]
I cannot. SonicPi does not need to know from which port it is receiving. Orca always communicates to SonicPi via `4559`.

You don't need to change anything in sonic pi, relating to which port data comes from, [as long as the OSC path is correct](https://github.com/hundredrabbits/Orca/blob/master/TUTORIAL.md#sonicpi).

**Comment by neauoire** [comment]
Oh wait, I might have misread what you were trying to do, are you sending data TOWARD ORCA from Sonic Pi? Orca doesn't not have a OSC listening port, but [it does listen](https://github.com/hundredrabbits/Orca#default-ports) for UDP via `49160`.

**Comment by nlebellier** [comment]
no you read well. I think the problem only occurs under linux but don't
have my tux friend with me right now.

**Comment by neauoire** [comment]
Donc SonicPi arrete de recevoir du OSC au hazard?

**Comment by nlebellier** [comment]
Ok you were right it's not your business it's a "issue" with osc path into Sonic Pi under linux. So the good way is to an * into the osc path in Sonic PI. 
```
live_loop :foo2 do
  use_real_time
  b = sync "/osc*/b"
  puts b
end
```
Sorry for the derangement :-)

**Comment by neauoire** [comment]
I'm curious, if you remove the `*` and just use `sync "/osc/b"` does it still work for you?

**Comment by nlebellier** [comment]
if you remove the * it doesn't work if you use sonic pi under Linux. https://in-thread.sonic-pi.net/t/osc-syntax-under-linux/2439?u=nlb

**Comment by neauoire** [comment]
That's very good to know :)

**Comment by nlebellier** [comment]
about OSC port in Sonic Pi, the next version will received data on 4560
port no more on 4559. If you build the spi 3.2dev from sources, don't
forget !
So your osc command in Orca is perfect to specify right now the osc port.
```osc:4560```
---
Nicolas
