### ISSUE TITLE
b should give us a C no ?

### ISSUE THREAD

**Issue by nlebellier** [hundredrabbits/Orca#126]
Hi

e gives us a F Fa
so b should gives us a C non ?

**Comment by neauoire** [comment]
You're right! There was a transpose error.
I've pushed an update that should fix this, you can test it with:

```
.4Cz.....................................
D4fzTCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsT.
.:02j....................................
```

**Comment by nlebellier** [comment]
oh ! what these notes H J ! A new notes notation ? Sure, I do miss something. Some explanations somewhere ?

**Comment by neauoire** [comment]
You can see the transpose table [here](https://github.com/hundredrabbits/Orca#transpose-table).

**Comment by nlebellier** [comment]
oups RTFD :-)

**Comment by nlebellier** [comment]
ok so 3H gives us a A on octave 4 A4. But 3H take 2 characters so how do you do to get worked with T as one character by space ?

**Comment by neauoire** [comment]
```
.4C......
D464THIJK
.:03J....
```

**Comment by neauoire** [comment]
If you really need to change the octave as well, you can use the `Q` instead of `T`, like [this](https://github.com/hundredrabbits/Orca/blob/master/examples/misc/popcorn.orca).
