### ISSUE TITLE
Removal of `&` operator? [discussion]

### ISSUE THREAD

**Issue by sixclones** [hundredrabbits/Orca#129]
A few days ago when I installed the software the operator `&` was describe as a way to receive inputs from Midi Controller. This has disappear now. May I ask why it was removed?

**Comment by neauoire** [comment]
I've made a big change on how midi works in orca, I temporarily disabled it today while I repaired it.
Give me a couple of hours and it will be back, as it was before.

**Comment by sixclones** [comment]
Ok, nothing urgent. ;)
Take the time that is needed, I'll wait.

**Comment by neauoire** [comment]
It's back :)
