### ISSUE TITLE
A operator can overflow into non base36 numbers

### ISSUE THREAD

**Issue by oueouiiaoo** [hundredrabbits/Orca#13]
Using the A operator passing Z and anything greater than 1 can produce midi, udp, comment or door operators; adding 6 to Z produces a 0, is this a bug ?

It produces some intresting results, but I'm not sure if this is intentional or not ?

![image](https://user-images.githubusercontent.com/22134042/50039317-7b5e9a00-0028-11e9-9c49-94209ddcbf3b.png)

[overflow.orca.txt](https://github.com/hundredrabbits/Orca/files/2682413/overflow.orca.txt)

**Comment by neauoire** [comment]
I guess I didn't think it a problem, but with `:`, and `;` locking ports, I've decided to limit to `y`, `z`, `*`, `a`, `b`... So `Az1 = *` and `Az2 = a`

**Comment by oueouiiaoo** [comment]
Thanks, it feels better having ```A``` only produce valid numerical outputs.
