### ISSUE TITLE
Suggestion : display the version name into guide section

### ISSUE THREAD

**Issue by nlebellier** [hundredrabbits/Orca#130]
As you work very hard on Orca (thanks again for all your work), may i suggest you to display the current version used into the guide or into the splash screen to know what version we do use. 

Something like display "orca 0.1--415e-commit "
Possible ?

**Comment by neauoire** [comment]
If you press `cmd+r`, you will see it displayed at the bottom.
The current version is 134.

**Comment by nlebellier** [comment]
Ok thanks for the tip !
