### ISSUE TITLE
howto make control the speed of i ?

### ISSUE THREAD

**Issue by nlebellier** [hundredrabbits/Orca#132]
Hi,

I increments right value with left value steps. But it works with the speed clock ? A solution to control this speed ? 
Cheers

**Comment by neauoire** [comment]
How about 
```
D..
.i4
.2.
```

**Comment by nlebellier** [comment]
Well this is not really what i want to get.
the question is how to control the speed of "next item".

```
.4C8.........
..28TCDEFGABb
....E........
D4..J........
.:02E14......
```

Let's say that i want to go two notes by two notes, can i do it with the I operator  or should i find a soluce with C ?

**Comment by neauoire** [comment]
Like this?

```
4C8..........
.0M2.........
..08TCDEFGABb
....C........
D4..J........
*:02C14......
```

**Comment by nlebellier** [comment]
Ok so the speed is given by the 4 on the right of D and the 4 on the left of the C. And multiplicate by the M operator. Ok so when do you use i operator since we can't control its speed ?

**Comment by neauoire** [comment]
When you need to increment something that does not need to be synced.

Like, you could have done this, same result, but not synced. I suspected that it was clocked so I gave you the solution with `C/M`.

```
..D4.........
..*..........
.2i8.........
..48TCDEFGABb
....G........
D4..J........
*:02G14......
```

**Comment by nlebellier** [comment]
ok now i now we can trigger the i operator... Merci !

**Comment by neauoire** [comment]
Yup.

Each letter of the alphabet is an operation,
lowercase letters operate on bang, uppercase letters operate each frame.

**Comment by nlebellier** [comment]
"Each letter of the alphabet is an operation,
lowercase letters operate on bang, uppercase letters operate each frame."

by the way where is it written ?

**Comment by neauoire** [comment]
It's the first line of the [documentation](https://github.com/hundredrabbits/Orca).

**Comment by nlebellier** [comment]
Oupss. Mille excuses.
