### ISSUE TITLE
UDP configurable IP

### ISSUE THREAD

**Issue by martinberlin** [hundredrabbits/Orca#135]
Hello Orca developers,
On the idea of building a new Addressable LED companion firmware for ESP32 Boards that may interface with Orca, I stumbled open that even using the same Port I had to edit the default localhost IP in : 
desktop/core/io/udp.js

**Would it be possible to add a custom UDP IP setting to the Orca menu ?**
I'm making a small open-source Firmware for the ESP32 and Addressable LEDs using the Neopixel library, that will receive UDP signals and launch fast animations in any addresssable LEDS stripe (for ex. WS2812B). The idea is that with less than 18 dollars you can get a controller, soldier 3 cables and get a working 144 Leds stripe that receives commands from Orca.

If someone has an idea to do it differently and for example hear on localhost all UDP entries starting with L for example, and redirect them somehow to CONTROLLER_IP, then it will be also possible to do it that way. 

The project is just starting, but it's testeable already, if someone wants to give it a try: 
https://github.com/martinberlin/Remora ( for now, demo in feature/animation branch)

**Comment by neauoire** [comment]
Hi @martinberlin :)
That's an amazing project, it's something I also use for my shows actually! And I always end up making a custom build for the live shows with the raspberry pi's IP. I've added a new command cmd `ip:`, that should make this easier.

https://github.com/hundredrabbits/Orca#udp
