### ISSUE TITLE
Question : what is a frame ?

### ISSUE THREAD

**Issue by nlebellier** [hundredrabbits/Orca#137]
Hi,

I have questions about what is frame ? I understand frame like this : 4 frames per beat ? Is it this ? 

How would you translate it in French ? Cadre, Image ?

Can we code into ternary ?

What about time command ? no comprendo what is it for ? 
You see i'm a bit confused among all this concepts ...
Cheers

**Comment by neauoire** [comment]
> I have questions about what is frame ?

The number of increments since application started. It's the value that control operators like `D`, `C`, `U`, etc.. I think a orca frame is 4 midi bars. Not sure tho, and I can double check now, you'll have to run your own tests.

> How would you translate it in French ?

Moment, instant, temps.

> Can we code into ternary ?

What are you trying to do?

> What about time command ?

This changes the frame value, it's a pretty advanced feature, I'll explain it to you when you start sending midi into orca, from orca itself, and that kind of complex behaviours. You shouldn't need to use that for now.

**Comment by nlebellier** [comment]
> I think a orca frame is 4 midi bars. Not sure tho
not clearer :-)

> Can we code into ternary ?

well if we want to have 3 frames in 1 beat ? to play triolet ? 

> time 
ok

**Comment by neauoire** [comment]
```
.3C3....
D323TCDE
*:03E...
```

**Comment by neauoire** [comment]
```
.3C3....
D323TCDE
*:03E...
```

**Comment by nobodycarestrue** [comment]
In Orca, a frame is equal to one 1/16th note. 

```
D1.....
*:01Cf1
``` 

In the above example, banging on every frame will bang on every 16th of a bar.

**Comment by nlebellier** [comment]
well it depends how many beats you think you have in one bar. If you consider 4 beats into one bar - noted in music 4/4 - ok every frame will bang on every 16th of bar so on every 16th of a bar, one sixteenth-note (une demi-croche en français)

For me it's clearer to say 
```
d:4 > every 1 beat 
d:2 > every half beat
d:1 > every quarter of one beat 
```
No ?

**Comment by nobodycarestrue** [comment]
It's all relative. Even your math takes you to 16th's. :-)

Since most time signatures are based around 4, I feel this is an easy way to comprehend a frame. You could do 3/3 time at 120 or so, but each trigger will still be translatable to a 16th note structure in relation to the set bpm.

**Comment by nlebellier** [comment]
But the question stays alive how to play 3 notes in one beat  ?

each note will last 0.333333 beat

Is it possible with Orca ? maybe not and it will be not very important
@neauoire can't get with your example

**Comment by neauoire** [comment]
I don't understand the question, sorry :/

**Comment by nlebellier** [comment]
Yes a quaver triplets as in your screenshot or a eighths triplet.

no always easy in english in french ? je veux juste savoir si on peut jouer des triolets de croches avec Orca donc 3 notes dans un temps ? Si on ne peut pas je m'en passerai :-) ce n'est pas grave

**Comment by neauoire** [comment]
I think the only way would be to increase the BPM, to work at double resolution.

**Comment by nlebellier** [comment]
to get eighths triplet ? ok so which code can give me quaver triplets :-)

**Comment by nobodycarestrue** [comment]
Unfortunately, you can't do triplets in Orca, only dotted. There's no way to bang in-between frames.

I think one would have to mess with the clock.js file and rework the bpm division to maybe get this to work? Yet then you'd be working in something based on 3 and may not be able to do regular sixteenth/eighth/quarter notes.

**Comment by nlebellier** [comment]
ok no problem :-) stay binary "simple basique" and have fun with Orca.

**Comment by neauoire** [comment]
<img width="372" alt="Screen Shot 2019-06-09 at 9 52 13 AM" src="https://user-images.githubusercontent.com/1455726/59156471-58271b80-8a9c-11e9-9533-9cbba23e4bf7.png">

Maybe use base 12, if you're going to work with triplets.
