### ISSUE TITLE
doc : dp will bang every 24th ?!

### ISSUE THREAD

**Issue by nlebellier** [hundredrabbits/Orca#140]
For instance Dp will bang every 24th frame. 
If we refer to the table https://github.com/hundredrabbits/Orca#base36-table
isn' it ``Do`` ?

**Comment by neauoire** [comment]
If you want to bang every 24th frame, use `Do`, as per:

```
Co.D3.....................
5oP.......................
..*..*..*..*..*..*..*..*..
Co.D6.....................
5oP.......................
..*.....*.....*.....*.....
Co.Dc.....................
5oP.......................
..*...........*...........
Co.Do.....................
5oP.......................
..*.......................
```

**Comment by nlebellier** [comment]
yes so there's a typo into the doc. 

> For instance Dp will bang every 24th frame.

it rather be "```Do``` will bang every 24th frame" right ?

**Comment by neauoire** [comment]
Ah! yes, next time, just go ahead and fix the typo as a pull request. 
It will be faster.

**Comment by nlebellier** [comment]
ok thank you !
