### ISSUE TITLE
feature : select a range then type to fill this selection

### ISSUE THREAD

**Issue by nlebellier** [hundredrabbits/Orca#141]
Hi,

when we select a range, it would be cool to type without for rach operand type enter and then right arrow to fill the selection.
"Just" an idea.
Cheers

**Comment by neauoire** [comment]
I don't understand, could you rephrase that, or write it in french?

**Comment by nlebellier** [comment]
Ok 
donc l'idée c'est de pouvoir sélectionner une plage et de taper directement et que chaque caractère s'inscrive et que le curseur passe à celui de droite automatiquement. 

Cela irait plus vite que la situation actuelle qui oblige à taper le caractère puis entrée puis flèche de direction vers la droite pour taper le second caractère. et ainsi de suite.
![feature-](https://user-images.githubusercontent.com/4880966/59271903-0aa1de80-8c55-11e9-832d-a354f1a6f424.gif)
C'est un peu pénible pour écrire notamment les commentaires entre #

Est-ce plus clair ? 
J'ai bien conscience que cela est sûrement plus facile à demander qu'à coder. C'est une idée.

**Comment by neauoire** [comment]
Ah! oui c'est bcp plus clair :)
Appuie sur `cmd i`, ca va te mettre en insert mode 👍

**Comment by nlebellier** [comment]
ok désolé... j'avais pas vu. 
bravo pour la rapidité dans le développement de ce feature :-)

**Comment by neauoire** [comment]
Sans probleme, c'est pas super bien documented cette feature.
