### ISSUE TITLE
Lowercase bang on it's output

### ISSUE THREAD

**Issue by echophon** [hundredrabbits/Orca#147]
If banging a lowercase that outputs a bang each frame, the lowercase will be banged by it's output - holding bang until manually reset.  This seems technically correct, but perhaps is an unintuitive use case.

Example:
```
.D.
...
.d1
...
```

**Comment by neauoire** [comment]
I think that will only affect `d1` and `1u1`, and I think this might actually be a good way of creating a sustained bang. I will not add a check for this, let's call it a qwerk

**Comment by echophon** [comment]
Sounds good.  I just thought I would point it out in case you thought differently.  Easy enough to work around. Cheers!

**Comment by neauoire** [comment]
Don't hesitate if you find other weird things like this, make issues. It's kind of nice to keep a list of these weird cases.
