### ISSUE TITLE
Question : can we change instrument in helm with sending a change control message

### ISSUE THREAD

**Issue by nlebellier** [hundredrabbits/Orca#148]
Hi,

i try to select an instrument in Helm (synthetizer) with Orca. Is it right to say if i send a change control with the value of zero, i can select a bank ?

Not very au point with midi but i found this doc in french https://www.emc.fr/upload/resource/pdf/30.pdf

Thanks

**Comment by neauoire** [comment]
the [midiCC](https://github.com/hundredrabbits/orca#midi-cc) operator in orca is `!`, so you'd need to use that, do you know the id of the control change to swap instrument in helm?

**Comment by echophon** [comment]
I can't find reference to Program Change support in the Helm manual https://tytel.org/static/docs/helm_manual.pdf   I don't think that many software synths support this message.  I am trying to switch sounds on hardware that supports Program Change but have been unsuccessful.  I think Program Change is actually a different type of message from CC in that two bytes are sent in the same msg - one for the bank & one for the patch.

If you are using a DAW, you might be able to create multiple Helm tracks and mute / unmute the track with midiCC.

**Comment by nlebellier** [comment]
thanks for your answer

Well i don't know the knob id used in Helm but i manage to change instrument in helm with a tinykey25 midi controller using the molette so maybe it's possible.

In general, is there a id knob convention ?

With Orca and helm, the way to use the cc operator is to send changing values and left button and learn assignment into helm. It works. then the link is made between Orca and Helm.

Really want to record some videos but Orca doesn't appear into OBS. Black screen... The issue seems to be due to electron (https://github.com/electron/electron/issues/16955) under windows 10.
Which software do you use to screenrecord Orca ?

**Comment by neauoire** [comment]
> i manage to change instrument in helm with a tinykey25 midi controller using the molette so maybe it's possible.

If you can find which values are sent, use the `!` controller. The convention for midiCC are written in the link [here](https://github.com/hundredrabbits/orca#midi-cc).

> Which software do you use to screenrecord Orca ?

I use Quicktime with loopMidi on OSX, and ffmepg on Linux. I don't have access to a Windows machine.

**Comment by nlebellier** [comment]
> It sends a value between 0-127, where the value is calculated as a ratio of 36, over a maximum of 127. For example, !008, is sending 28, or (8/36)*127 through the first channel, to the control mapped with id0. You can press enter, with the ! operator selected, to assign it to a controller. 



> By default, the operator sends to CC64 and up, the offset can be changed with the command cc:0, to set the offset to 0.

sorry to be dumb but i don't understand this sentence. "sends to CC64"...

**Comment by neauoire** [comment]
there's 128 addresses in OSC, maybe 255, I forget. But there's only 36 values in orca, so it sends from  64 to 164.

**Comment by nlebellier** [comment]
``` ffmepg on Linux ```
maybe i can get your linux command to try myself ?

**Comment by neauoire** [comment]
https://trac.ffmpeg.org/wiki/Capture/Desktop

**Comment by okyeron** [comment]
FWIW I will have a PR for midi program change coming shortly.

**Comment by nlebellier** [comment]
ok cool !
Could you give some examples of daw or others software supporting this kind of message ?

**Comment by okyeron** [comment]
Program Change is an old school but pretty typical thing for hardware synths. 

Apparently Ableton does not support incoming program change messages, but here's an [Ableton Help Article](https://help.ableton.com/hc/en-us/articles/209070489-How-to-send-Program-Change-messages-from-Live) about **sending** program change messages. And [another with Logic](https://support.apple.com/kb/PH13114?locale=en_US)

Read more about all these messages [on the MIDI website](https://www.midi.org/articles-old/about-midi-part-3-midi-messages).
