### ISSUE TITLE
Possible to make F (if) to work strictly 

### ISSUE THREAD

**Issue by martinberlin** [hundredrabbits/Orca#149]
![F-strict](https://user-images.githubusercontent.com/2692928/60071749-7c7d2c00-971b-11e9-97d1-cff5d2934277.png)
What I'm trying to expose it's if add an F operator
 .F.  I would like that the left (a) can also compare a note like C without C converting into a Counter itself. Like a strict mode where the first that takes the space will domain over this 2 dot parameters. So adding there a C (a) value will not make Orca think it's a counter but just the a value of the F since the if was there first.
It would possible to do something like this or I'm just doing things wrong there trying to compare a C?

**Comment by neauoire** [comment]
Do this:

<img width="223" alt="Screen Shot 2019-06-25 at 2 38 00 PM" src="https://user-images.githubusercontent.com/1455726/60071951-df3fe900-9756-11e9-94bf-0ead702667ee.png">

**Comment by martinberlin** [comment]
Oh was so simple. Sorry for the dumb question!

**Comment by neauoire** [comment]
There are no dumb questions :)
