### ISSUE TITLE
optional extension for graphic command

### ISSUE THREAD

**Issue by MAKIO135** [hundredrabbits/Orca#151]
Since using `.gif` / `.png` with the `graphic` command is the reason for multiple forks, setting extension could be optional:
```javascript
'graphic': (p) => { terminal.theme.setImage(terminal.source.locate(p.parts[0] + '.' + (p.parts[1] || 'jpg'))) },
```
`.jpg` would still be the default extension, thus not breaking anything, but anyone could use `.gif` and other supported formats for `background-image` (PNG, SVG, JPG, GIF, WEBP)  

-> Usage: `graphic:1;gif`

Instead of the current fixed `.jpg` extension:
```javascript
'graphic': (p) => { terminal.theme.setImage(terminal.source.locate(p.str + '.jpg')) },
```
https://github.com/hundredrabbits/Orca/blob/21a5b46829555fb3f42d999cac256967dec951be/desktop/sources/scripts/commander.js#L42

**Comment by nlebellier** [comment]
Hi,

Good idea i propose a shorter syntax

```;graphiq:1;g``` - g for gif
```;graphiq:1;s``` - svg
```;graphiq:1;p``` png

default stays to jpg.

**Comment by neauoire** [comment]
I like it, I think the full extension is better so I don't have to make changes anytime someone want to add a new one.

**Comment by MAKIO135** [comment]
Yes, plus prevents `jpg`/`jpeg` errors

<http://makio135.com/>


Le ven. 28 juin 2019 à 11:44, Лu Лinveгa <notifications@github.com> a
écrit :

**Comment by MAKIO135** [comment]
Yes, plus prevents `jpg` / `jpeg` errors

**Comment by neauoire** [comment]
Implemented `$gr:name;ext`, also implemented a `$` operator that automatically sends an operator to Orca, without going through UDP!

**Comment by martinberlin** [comment]
The $ dollar sign definitely does not work on my Ubuntu PC.
The only things I can see with SHIFT pressed and the numbers are: !%

Or this only though to be like a command using Ctrl+K?

**Comment by neauoire** [comment]
no, you're supposed to be able to type the `$` character into the grid. Dunno why it's not working for you.

**Comment by martinberlin** [comment]
It's maybe something to do that I'm using Gnome and Ubuntu 18? Did someone tried this on Ubuntu?
But the funny thing is that it works on the command Orca CTRL-K so it's really strange I would love to know if someone else can help me out find what it is, since it's really bugging me.

**Comment by MAKIO135** [comment]
Which version number of Orca are you using?

**Comment by martinberlin** [comment]
The last one that is available on master branch

**Comment by martinberlin** [comment]
Everything working as expected. Turns out apart of pulling latest master I had to make a npm install to get the latest vendor updates. Is working as expected now many thanks to all the team

**Comment by neauoire** [comment]
I'm glad to hear :)
