### ISSUE TITLE
Question : what is apm ?

### ISSUE THREAD

**Issue by nlebellier** [hundredrabbits/Orca#152]
Hi,

Could you explain the goal of the apm command ? What's the difference with bpm ? what do you mean by _animates_

bpm:140 Sets bpm speed to 140.
apm:160 Animates bpm speed to 160.

**Comment by neauoire** [comment]
Try it! You'll see :)

**Comment by nlebellier** [comment]
i have tried it but for both it changes the beat per minute so i sure miss something that's why i ask...

**Comment by neauoire** [comment]
really? That's a problem.

## Try

- `cmd k`, type `bpm:140`, press `enter`.

When you do this it animates the BPM to 140?

**Comment by nlebellier** [comment]
ah ok i catch it

i put ```bpm:60``` to set beats per minute to 60 and then ```apm:240``` and so the bpm will be increased ("_animate_")from 60 to 240. 
Ok !
