### ISSUE TITLE
CC, Program Change & Pitch Bend should each be their own operator?

### ISSUE THREAD

**Issue by nobodycarestrue** [hundredrabbits/Orca#156]
Just tried this new CC and would it not be better if each were their own operator? Maybe `(` & `)` could be used?

If only to fit in with Orca's design flow, selecting the operator's function after the values seems backwards from regular Orca logic.

Also, to do program change properly, there needs to be 3 values: bank, sub & pgm. Because of Orca's 36 limitation, some kind of pgm offset command (similar to the CC offset command) would also need to be implemented. 

Something like `(abcd` maybe? 
`a` = midi channel 
`b` = bank
`c` = sub
`d` = pgm
Cmd+k: `pgm:xx` to select the starting pgm value

And then with pitch bend, something like `)ab` maybe?
`a` = midi channel
`b` = pitch bend value

**Comment by neauoire** [comment]
`&` is keys.

I really don't know what or how to use program change and pitch bend, so I must rely on how you want to use it. I'm not even sure how to use it, I don't have any device that supports these 3 things, even midi CC.

**Comment by nobodycarestrue** [comment]
Oh, I know `&` = keys. I'm only suggesting the other 2.

`!` = CC
`(` = Program Change
`)` = Pitch Bend

Also, don't you use Ableton Live or a similar DAW? All these can be tested in there with almost any VST synth.

**Comment by neauoire** [comment]
I don't have any VST, but if you can show me how to test with the built-in instruments I'd love to learn.

**Comment by nobodycarestrue** [comment]
Ok, I'll find a free VST to test program change on.

For CC though, super easy in Live (or any similar Daw). 

For Live {note: Orca should be stopped while doing this or anything being banged will be selected}:
- click any parameter(knob/value) that you want to control in Live
- press `cmd+m` (or right click 'edit MIDI map') to open MIDI mappings
- on Orca side, select your CC operator. Place the cursor on the `!` of something like `!000` and press return
- on Live side, you should now see CC 64 mapped to that parameter
- press `cmd+m` again to close the MIDI mappings and Orca will now be controlling that parameter

**Comment by neauoire** [comment]
Okay yes that works :)
is it possible to test pitch bend with the simpler?

**Comment by nobodycarestrue** [comment]
Something like Helm (https://tytel.org/helm/) can be used to test program change on.

**Comment by nobodycarestrue** [comment]
Can totally test pitch bend with a simpler. Just load up a simpler and then with `!0002` changing the third place value will bend pitch.

**Comment by nobodycarestrue** [comment]
<img width="236" alt="Screen Shot 2019-07-02 at 4 06 40 PM" src="https://user-images.githubusercontent.com/47595933/60552369-62c38200-9ce3-11e9-8506-8b05f1913883.png">

For comparison, this is how Live uses program change within clips.

For some synths, just the pgm change value will work, but anything with banks or presets, one needs to enter at least a sub & pgm value (bank usually defaults at 1).

**Comment by okyeron** [comment]
FWIW - I've not tried it, but an Abelton support page said that it only sends program change messages, but does not receive them.

**Comment by nobodycarestrue** [comment]
> FWIW - I've not tried it, but an Abelton support page said that it only sends program change messages, but does not receive them.

This is correct. Only things with presets can accept program change messages.

**Comment by nlebellier** [comment]
> Something like Helm (https://tytel.org/helm/) can be used to test program change on.

Have you really tried or you just suppose ? An example of Orca Code to test in real life :-)
Cheers

**Comment by neauoire** [comment]
After some thinking on this, here's my suggestion:

- I have reverted `cc` to how it was before `!039`.
- Pitch bend should be its own operator, I am using `?03` for the time being.
- Program change should be a commander action, accessible like `$pg:0;127;64;32`

**Comment by nobodycarestrue** [comment]
> After some thinking on this, here's my suggestion:
> 
> * **Midi Pitch Bend** is now its own operator, using `?03`.
> * **MidiCC** was reverted to how it was before `!039`.
> * **Midi Program Change** should be a commander action, accessible like `$pg:0;127;64;32`

That sounds pretty golden to me. :-)

**Comment by neauoire** [comment]
I'll need some help re-implementing and testing the pitch bend :3

<img width="598" alt="Screen Shot 2019-07-12 at 9 53 43 AM" src="https://user-images.githubusercontent.com/1455726/61094655-09014b80-a48b-11e9-955a-65f2512bd953.png">

**Comment by nobodycarestrue** [comment]
No problem testing here. I'll keep checking to see when it's up.

Curious though, what synth do you have? Pitch Bend & CC should be doable on 99% of synths out there.

**Comment by nobodycarestrue** [comment]
I believe @okyeron did use `0xe0`, no?

https://github.com/hundredrabbits/Orca/blob/dbba3d9756da883c1853f119054898442ff4aaaa/desktop/core/io/cc.js

**Comment by neauoire** [comment]
Oh, my mistake 👍

**Comment by neauoire** [comment]
I have the Elta Polivoks, super lo-fi.

**Comment by nobodycarestrue** [comment]
Is it the mini? This one: https://docs.wixstatic.com/ugd/12d408_e1fe272446a34f82b0a632b1bec9095c.pdf

**Comment by neauoire** [comment]
Yup.

https://wiki.xxiivv.com/Studio <https://wiki.xxiivv.com/Studio>

**Comment by nobodycarestrue** [comment]
Cool, so CC looks easy to do with those instructions and using the `channel` button on the back.

And according to Elta on a Muff Wiggler post (https://www.muffwiggler.com/forum/viewtopic.php?t=200670&sid=8a429ae680091f5a05aa59a6d130d4a4):

> 
From Elta: Hello! The midi implementation is quite simple in Polivoks mini. It is a Pitch CV, Gate, MOD MIDI CC to filter cutoff. Pitch bend range is +/- 1 octave. Note priority is last note, Legato mode. LFO is independent from MIDI and Gate signals. No velocity.
--

Reading that, I imagine pitch bend will work as normal using the standard pitch bend message.

**Comment by neauoire** [comment]
That is cool! I had no idea, I will try it out with orca. Thanks for the head's up.

**Comment by nobodycarestrue** [comment]
Tested what pitch bend you have so far and I think you need to send 2 values (LSB & MSB). I think @okyeron pitch bend was sending a default 0 LSB? Reason why only 1 value needed input for it to work? If not LSB, maybe MSB was defaulted to 127?

**Comment by okyeron** [comment]
>Midi Program Change should be a commander action, accessible like $pg:0;127;64;32

I'm gonna try this one more time and then I'm out

This should called **Bank Select** NOT Program Change. It's Bank Select if you're sending those three bytes.

Pitchbend is 0xe0 + channel (0xe0 thru 0xef) with an LSB (data[1]), and MSB (data[2])

**Comment by nobodycarestrue** [comment]
> This should called Bank Select NOT Program Change. It's Bank Select if you're sending those three bytes (according to the MIDI Spec)

This is true. We would be sending both Bank Select & Program Change messages. So could call it `bs`, `pc` or `bspc`, but maybe `preset`(`pr`) would be better?

**Comment by okyeron** [comment]
#159 fixes pitchbend implementation.

this probably needs some offsets to get the full range of pitchbend, but not sure that should be the same or different from CC offsets.

**Comment by nobodycarestrue** [comment]
Works perfect on this side @okyeron Excellent work. :-)

Getting a full 0-127 range with the MSB value position. Looks like nothing I have uses the LSB side, but I imagine some old hardware may require and be able to utilize it.

**Comment by neauoire** [comment]
Excellent work @okyeron! I think we finally have something pretty sturdy.

**Comment by nobodycarestrue** [comment]
Also, Pitch Bend is looking really nice in VCV Rack. Super beautiful. :-)

<img width="870" alt="Screen Shot 2019-07-11 at 11 22 59 PM" src="https://user-images.githubusercontent.com/47595933/61106754-ef341a00-a432-11e9-8464-5236abb0048e.png">

**Comment by okyeron** [comment]
Right on.

I think you should get finer grain control also using lsb, but not sure how best to code that in Orca yet.

**Comment by neauoire** [comment]
Added `pg:` command the commander, can be triggered with:

```
$pg:12;12;12;12
```

<img width="472" alt="Screen Shot 2019-07-12 at 3 36 27 PM" src="https://user-images.githubusercontent.com/1455726/61107463-f141bb80-a4ba-11e9-9340-24ecca3405b8.png">

Also updated Electron versin.

**Comment by nobodycarestrue** [comment]
Not getting any change on any synth, but did notice any letter value is sending a `NaN`?

<img width="1154" alt="Screen Shot 2019-07-11 at 11 55 41 PM" src="https://user-images.githubusercontent.com/47595933/61108550-69ff3400-a437-11e9-9da7-c75dd1c3d107.png">

Also, not sure if could cause a problem, but noticed that 0 sends a midi channel 0 instead of a 1 like a `:03C` would.

**Comment by nobodycarestrue** [comment]
Not sending any midi signal, but getting the same thing in console.

<img width="1154" alt="Screen Shot 2019-07-11 at 11 58 32 PM" src="https://user-images.githubusercontent.com/47595933/61108681-ded26e00-a437-11e9-9991-c5e42a53d695.png">

**Comment by neauoire** [comment]
It's not implemented yet, it's kind of like a mockup.
I don't really know how to implement it, I've just put the blocks needed so @okyeron can connect this to the working code :)

**Comment by nobodycarestrue** [comment]
Very cool. Looking like a good start then. :-)

**Comment by okyeron** [comment]
bank select and program change implemented #160

You can do just program change alone (or program change + bank) by leaving bank or sub empty like `pg:0;;;1` or pg:0;1;;1

Tested on my Blofeld - works well. The Blofeld does not seem to use the `sub` so maybe some testing is needed on something that has more sub-banks.

**Comment by okyeron** [comment]
Is there a way to constrain the input value for channel to 0-15? a value of 16 throw an error:
`Uncaught TypeError: Failed to execute 'send' on 'MIDIOutput': Running status is not allowed at index 2 (0).`

**Comment by neauoire** [comment]
Yup, it's clamp, I can add this to your PR don't worry about it :)

**Comment by okyeron** [comment]
Further documentation note:

Bank is MSB, Sub is LSB

some synths apparently will list MSB+LSB values in their midi implementation charts. bank/sub terminology seems to be Ableton-centric

**Comment by neauoire** [comment]
I've clamped **channel** `0-15`, and **pgm** `0-127`.

**Comment by neauoire** [comment]
I believe that we can finally close this issue! 
🥇 @okyeron

**Comment by nobodycarestrue** [comment]
Sadly, doesn't work for me. Only the program change part works.

Also, something seems to have broken the regular midi note `:` operator? Can no longer change octaves.

**Comment by neauoire** [comment]
Sorry about that, just fixed the octave issue with the `:` & `%` operators.

**Comment by neauoire** [comment]
So pitch bend has stopped working?

**Comment by nobodycarestrue** [comment]
Pitch Bend still works. Just the Bank stuff doesn't work.

**Comment by nobodycarestrue** [comment]
Actually just got it working. MSB has to be set to 0 for me. :-)

**Comment by nobodycarestrue** [comment]
> Sorry about that, just fixed the octave issue with the : & % operators.

Octave seems to work, but can bang a note without a note selected?

```
D2.
.:0
```

**Comment by nobodycarestrue** [comment]
Also, banging `$pg` while also banging a note seems to mute the note. Is this normal?

**Comment by okyeron** [comment]
> Sadly, doesn't work for me. Only the program change part works.

Can you post the code you tried and what device you're tying to control? It's possible the device implementation of msb/lsb is different?

**Comment by okyeron** [comment]
> Also, banging `$pg` while also banging a note seems to mute the note. Is this normal?

from: https://www.yamahasynth.com/motifxf-category/bank-select-and-program-change
>You cannot have the Motif XF change programs in the middle of a note, nor can you have it change programs and play a note simultaneously... therefore, a musically appropriate time is one where the instrument change does not negatively affect the music you are hearing. If there is a musical rest (pause) of approximately a 64th note you can usually insert a Program Change event. That is much faster than a human being can actually switch instruments.

**Comment by nobodycarestrue** [comment]
I got it working. Just needed to use the LSB section.
```
D1........1Ba
*$pg:0;0;2;8.
```

**Comment by okyeron** [comment]
Again - what synth are you using?

FWIW - Just tested with Helm and from the commander `pg:0;;;8` works just fine. 

So maybe this is an issue using the $ operator?

**Comment by nobodycarestrue** [comment]
Oh nice, just tested with Helm and no note mutes. Must depend on the synth. :-)

**Comment by okyeron** [comment]
banks select/program change are very dependent on the order multiple control messages are received. Its VERY likely that sending a note message at the same time would screw this up.

**Comment by nobodycarestrue** [comment]
```
D1.....
*:03C..
.......
D1.....
*$pg...
```

Just noticed that this stops all midi output out of Orca. Getting this error in the console.

<img width="697" alt="Screen Shot 2019-07-12 at 6 43 20 PM" src="https://user-images.githubusercontent.com/47595933/61165403-ed229780-a4d4-11e9-85ee-abb5dd2d7792.png">
.

**Comment by neauoire** [comment]
Oh! Going to fix that.

**Comment by neauoire** [comment]
Pushed an update that makes sure a device is accessible.

**Comment by okyeron** [comment]
more updates/fixes. @nobodycarestrue can you test again?

**Comment by nobodycarestrue** [comment]
Just tested and everything seems to be working pretty well. Excellent work all. :-)

Here's a little example of everything controlling Helm and a couple effects.

[miditest.mov.zip](https://github.com/hundredrabbits/Orca/files/3388578/miditest.mov.zip)

**Comment by neauoire** [comment]
Seeing the `Z` at the bottom right moving like this got me like "wait, how OLD IS THIS VERSION"
very cool demo

Shall I go ahead and close this monster?

**Comment by nobodycarestrue** [comment]
Everything's looking pretty good on this side. Have tried a bunch of tests and all the results seemed golden. 

Once again, super excellent work @okyeron & @neauoire. :-)
