### ISSUE TITLE
Make all notes accessible from the keys operator

### ISSUE THREAD

**Issue by neauoire** [hundredrabbits/Orca#166]
See #165

**Comment by okyeron** [comment]
Dumb idea? Could `&` have 2 outputs? One for `Note Value` (A-G) and one for `Octave`?

**Comment by neauoire** [comment]
not a fan.. I'll make an orca example that will show how to convert any outputted letter into a note.

**Comment by neauoire** [comment]
Removed the keys operator entirely, for now.
