### ISSUE TITLE
Clock is all messed up

### ISSUE THREAD

**Issue by nobodycarestrue** [hundredrabbits/Orca#169]
Just downloaded the latest version of Orca and the clock is all messed up. Can't change bpm and frames go crazy when using the `cmd + >`/`cmd + <`.

**Comment by neauoire** [comment]
I'll have a look.

**Comment by neauoire** [comment]
Oh wow, I can confirm, the shortcut breaks the clock. 
I'll fix that.

**Comment by neauoire** [comment]
There was a duplicated function `setTimer`, that should work properly now :)
Could you have a look?

**Comment by nobodycarestrue** [comment]
Just tested & seems fixed. Can now adjust bpm as regular.

Unfortunately, bpm doesn't seem steady. Bpm seems to speed up over time or is outputting a higher bpm than stated (maybe 171 when set to 170)?

This could be an issue that has been there for a while, just don't remember it being so bad before.

**Comment by nobodycarestrue** [comment]
So very weird. Everything seems ok now. 

Ran through a bunch of tests and as soon as I soon as I put a `D2` along with a `D1` everything fell in place. Not sure what happened there.

**Comment by neauoire** [comment]
Testing atm. If I tap to bpm it seems pretty stable-ish.

**Comment by nobodycarestrue** [comment]
How do you tap to tempo?

**Comment by neauoire** [comment]
I have a node script that detects bpm from midi signal.

**Comment by nobodycarestrue** [comment]
Ahhh. 

Just noticed that you can now send Midi clock from Orca out.
 
<img width="619" alt="Screen Shot 2019-07-17 at 10 49 52 PM" src="https://user-images.githubusercontent.com/47595933/61432393-31eb6b80-a8e5-11e9-8c50-2cbfa3e3342e.png">

As you can see in the pic above, 104 in Orca is actually 104.17. 

<img width="619" alt="Screen Shot 2019-07-17 at 10 51 39 PM" src="https://user-images.githubusercontent.com/47595933/61432472-724ae980-a8e5-11e9-982d-3df0eff4e4bd.png">

Changing from 104 to 105. Orca actually then sends 105.63. 

This would explain why things would get out of sync for me.

**Comment by nobodycarestrue** [comment]
<img width="619" alt="Screen Shot 2019-07-17 at 11 00 34 PM" src="https://user-images.githubusercontent.com/47595933/61432896-b12d6f00-a8e6-11e9-953b-e590ae8e9f07.png">

120 to 121 is then 121.96 (basically 122).

**Comment by nobodycarestrue** [comment]
<img width="619" alt="Screen Shot 2019-07-17 at 11 07 37 PM" src="https://user-images.githubusercontent.com/47595933/61433273-b0490d00-a8e7-11e9-9271-a906558a1c1a.png">

Maybe the faster the bpm the more unstable? Here's 201 outputting 202.69.

**Comment by neauoire** [comment]
It's normal I think that has the time between frames get shorter, it becomes more inaccurate. I don't know how I could make this more reliable with my current programming skills.

**Comment by nobodycarestrue** [comment]
No worries. Just something that's good to know. :-)

Being able to sync to Orca or for Orca to sync up to something else makes this not that big of a deal. Just something that one needs to know when recording and working with multiple setups.

**Comment by neauoire** [comment]
It only took a whole year almost before Orca got clock in and clock out, BUT WE DID IT

**Comment by nobodycarestrue** [comment]
For sure. ✊
