### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by secretgspot** [hundredrabbits/Orca#170]
tried npm version and prebuilt windows 64 version, no sound is coming out.

**Comment by neauoire** [comment]
No audio coming out of what, Orca?
Orca doesn't make sounds.

If I misunderstood the question, please let me know which DAW you're using with Orca, or have a look at the tutorials [here](https://github.com/hundredrabbits/Orca/blob/master/TUTORIAL.md) to setup orca.
