### ISSUE TITLE
color command question

### ISSUE THREAD

**Issue by nlebellier** [hundredrabbits/Orca#171]
Hi,

just try to use color command 

what are the parameters of this command ?

````
D

$color:633;fff;60f 

```

When i use prompt command everything becomes grey and even i change values.
an idea of what happens ?
greets

**Comment by neauoire** [comment]
You are correct, there was an error with the color command.
The 3 values are supposed to be hexadecimal color codes, either 3 or 6 characters long.

**Comment by nlebellier** [comment]
thanks !
first value is for ? second value is for ? third value is for ?

**Comment by neauoire** [comment]
`color:red;green;blue`

**Comment by timoffenhaeusser** [comment]
When I change those color values, highlight2 and highlight3 I can see changing the code and all. But on my version the highlight1 value doesn't seem to effect anything. I'm using Orca on macOS. What is the highlight1 color for?
Thanks, Tim.
