### ISSUE TITLE
Issue typing the & and $ characters.

### ISSUE THREAD

**Issue by martinberlin** [hundredrabbits/Orca#173]
Devine,
would it be possible to enable pointing with the mouse and going to a certain part of the grid in Orca?
The second question is: 
Why there are some characters that do not work when pressing shift and the numbers?

For example, is impossible for me to use:
& keys(channel)
or
$ self: Sends a command to itself.

And that's at the moment quite a show stopper.

**Comment by neauoire** [comment]
I dunno, are you getting errors in the console when you try typing these 2 characters?

**Comment by martinberlin** [comment]
No not at all. Do I need to start npm in debug mode or anything alike?
Typing CTRL+K I can type these characters in the command status bar. So it must be something in the grid itself that is preventing me to use them

**Comment by neauoire** [comment]
No, you can just press `cmd .` to see the console.

**Comment by martinberlin** [comment]
No errors at all. In fact inside Orca works but only on the command console (CTRL+K)
So it should be some filter avoiding it to appear in the grid.

**Comment by martinberlin** [comment]
Very sorry, my bad because my master was old, now it works as expected. It was just an older version!
