### ISSUE TITLE
How to add semitones to notes?

### ISSUE THREAD

**Issue by robmckinnon** [hundredrabbits/Orca#174]
Is there a technique for adding semitones to notes in ORCΛ? 

E.g.
- add 0 semitones to note `C` to keep `C`
- add 1 semitone to note `C` to get `c`, i.e. C sharp
- add 2 semitones to note `C` to get `D`

The **A**dd function does not work for adding semitones, as it is doing numerical arithematic. E.g.

```
H    H    H
CA0  CA1  CA2
 c    d    e
```

**Comment by neauoire** [comment]
I recommend look at [this thread](https://llllllll.co/t/orca-livecoding-tool/17689/439) for some ideas.
