### ISSUE TITLE
can't write full ip into commander

### ISSUE THREAD

**Issue by nlebellier** [hundredrabbits/Orca#175]
Hello,

Under ubuntu 18.04.03, i can't type the full ip but when inspect the character are well written.

![image](https://user-images.githubusercontent.com/4880966/66718523-312f7c00-ede5-11e9-9f7f-ed2b5bfd5d19.png)

**Comment by neauoire** [comment]
huh, that doesn't look like a valid IP address.

**Comment by nlebellier** [comment]
si si the address i want to type is 192.168.1.109 and i don't see the 9 into the commander zone so of course i type several times to ensure there is a bug. ok ?

**Comment by neauoire** [comment]
Oh, let me have a look.

**Comment by neauoire** [comment]
Weiiiird, works for me if I type it:

<img width="409" alt="image" src="https://user-images.githubusercontent.com/1455726/66718723-eb5abf80-edb4-11e9-915e-cfd49dd185f6.png">

**Comment by nlebellier** [comment]
wait a minute please not sure i'm working with the latest version...

**Comment by nlebellier** [comment]
Oups sorry with the latest version no problem
