### ISSUE TITLE
Under linux after last update I cannot launch File manager to open an .orca

### ISSUE THREAD

**Issue by martinberlin** [hundredrabbits/Orca#180]
Using latest develop pulled from git I cannot open anymore an Orca file. Before it had some issues but not like this (Like the File Manager was stuck and I could not be closed)
For the record, using Ubuntu 18, that comes with Gnome.

To reproduce if someone is using this on Linux. Just open with: npm start
Go to File in top menu, or CTRL+ O, Nautilus file manager is not opening for me so I cannot open any file. 
@neauoire is it possible to start it somehow with a .orca file from command line using npm?

**Comment by neauoire** [comment]
hi Martin, I will have a look at this right now. I made some changes with that how that was handled. It works for me on linux tho(elementary). Are you getting an error in the console?

You can also open a file by dragging it over the window, I will also implement a file loading via npm command line.

![Screenshot from 2019-10-30 16-56-44@2x](https://user-images.githubusercontent.com/1455726/67898236-4ff87700-fb36-11e9-9f9e-3647581a000a.png)

**Comment by neauoire** [comment]
It's possible that your electron version is out of date, could you try npm install again?

**Comment by martinberlin** [comment]
Hello!
npm list electron
Orca@0.1.0
Seems up to date.

Console says:
```
Uncaught TypeError: dialog.showOpenDialogSync is not a function
    at Source.open (source.js:29)
    at terminal.js:58
    at fn (controller.js:17)
    at CallbacksRegistry.apply (/home/martin/Documen…acks-registry.js:47)
    at /home/martin/Documen…r/api/remote.js:287
    at EventEmitter.<anonymous> (/home/martin/Documen…r/api/remote.js:277)
```

**Comment by neauoire** [comment]
weird, `dialog.showOpenDialogSync` is [definitely a function](https://electronjs.org/docs/api/dialog) in the last electron. So `npm install` didn't fix it, could you try removing the node_modules folder and installing it again?

**Comment by martinberlin** [comment]
That was it!
Orca/desktop$ npm update

> electron@7.0.0 postinstall /home/martin/Documents/PlatformIO/Projects/Orca/desktop/node_modules/electron
> node install.js

For some reason even that your package definition and the package.lock seems correct an npm install was not updating electron for me. Well anyways I've always had a love and hate relationship with dependency managers. Maybe was just my local issue with npm please feel free to close this one.
Nice upgrade now seems to play better with Nautilus!

**Comment by martinberlin** [comment]
Here it's a nice way to make a handy Orca link in Linux desktop.
Orca/desktop$ npm run build_linux
After building the Electron application just create a file named: Orca.desktop  in your desktop adjusting the path to your Orca folder / icon

```
[Desktop Entry]
Name=ORCΛ
GenericName=ORCΛ Sequencer
Exec=/home/martin/Programs/Orca-linux-x64/Orca
Icon=/home/martin/Programs/Orca-linux-x64/resources/app/icon.png
Terminal=false
Type=Application
Categories=Midi;Education;Music;
Comment=ORCΛ
GenericName[en_US.UTF-8]=Orca
Comment[en_US.UTF-8]=ORV
Name[en_US]=Orca.desktop
```
Then you can just open this with a click in the desktop!

**Comment by martinberlin** [comment]
Thanks @neauoire ! Please send me a short message if the Remora arrives. Closing this since it seems was just my problem with npm install. Just reopen if someone has the same issue.
