### ISSUE TITLE
Version number prints in lower left for first 16 frames

### ISSUE THREAD

**Issue by bbarham** [hundredrabbits/Orca#184]
Minor issue but it might be better to put this info somewhere in the menu system.
If I do something like this:
4Dw....
..$ti:0
It prints every time the frame count resets to zero obscuring operator info.

**Comment by neauoire** [comment]
aaaah I hadn't think of that. I'll fix that.
I'm just curious tho, why do you reset the time like that?

**Comment by bbarham** [comment]
I was trying to find a way to re-sync increment operators on a slow clock. The clock operators are always a modulo of the frame count so when frame count is zero all clocks are reset. The increment operators are independent of both the frame count and each other. They only start at their zero when they are created or loop back around.

**Comment by neauoire** [comment]
You could use something like `1x0` over the incrementer, if you bang it, it will reset the incremented value.

```
aV...............
.................
.......Va..Va..Va
.................
......1x0.1x0.1x0
.......I...I...I.
.......n...a...y.
```

**Comment by bbarham** [comment]
Ohhhh! Yes - you did mention in your workshop that increment reads its output. very clever!

**Comment by neauoire** [comment]
I think I like this behaviour better than anything else I can think of.
I'll close this for now.
