### ISSUE TITLE
Sequencing CV?

### ISSUE THREAD

**Issue by mxmilkb** [hundredrabbits/Orca#192]
JACK (and LV2 have) CV ports, something that has seen more support [recently](https://linuxmusicians.com/viewtopic.php?f=1&t=20701).

Might this be a audio rate control method that Orca could support the sequencing of?

**Comment by neauoire** [comment]
The best way to do this would be to use a companion application and convert UDP or MidiCC messages to control voltage I think, I don't think it should be part of orca itself.

**Comment by neauoire** [comment]
@mxmilkb you might be interested in this, it's a norns' orca fork that supports crow, designed to play with VC.
https://github.com/CoolLeRue/orca
