### ISSUE TITLE
Load Operator Extensions

### ISSUE THREAD

**Issue by ryanramage** [hundredrabbits/Orca#194]
I have some code in progress that would allow orca to load extensions to the library.

Motivation:
Orca has a very limited set of operators. This is a good thing®. It focuses the user on basic use out of the box. Also most user keyboards only have access to so many letters, and orca is running out of available characters.

But,
There are times that a user wants to extend the set of operators. It would allow for some really unique customizations or shorthands that don't need to be added to the orca.

I propose an way in orca that a user can load a set of operators that are custom, and dont have to be compiled in. It would be commander command, 'extend', which would load a js file at runtime and add the operators to the library.

Here is an example of what it might look like: custom.orcas

```
export const load = (Operator) => {
  const extensions = {}

  extensions['Φ'] = function Operator_ (orca, x, y, passive) {
    Operator.call(this, orca, x, y, '_', passive)

    this.name = 'niff'
    this.info = 'Reads offset, bangs if equal to char'

    this.ports.x = { x: -2, y: 0 }
    this.ports.y = { x: -1, y: 0 }
    this.ports.comparison = { x: 1, y: 0 }
    this.ports.output = { x: 0, y: 1, bang: true }

    this.operation = function (force = false) {
      const x = 0 - this.listen(this.ports.x, true)
      const y = 0 - (this.listen(this.ports.y, true) + 1)
      this.ports.val = {x, y }
      const a = this.listen(this.ports.comparison)
      const b = this.listen(this.ports.val)
      return a !== b
    }
  }
  return extensions
}
```
This style of exports works better for a dynamic load in a browser and node environment.

Risks
Orca is already running out of space for operators. Its hard to find available chars to extend. I propose that extensions are in the unicode space, so that there is no interference between extensions and normal orca operators. Currently its not easy to enter unicode in Orca, (I have to use something like  https://unicode-table.com/en/#03A6 and copy and paste) but I've proven it works fine. In some future it might be nice to have a way to help users put unicode chars in, (like a selector) but I will leave that to the futue.

I would like to pursue this as a merge request, I just want to make sure that @neauoire you'd be open to this as I don't want to have a lot of time invested and not have it available to the community. I think it would open up Orca to some amazing things.

**Comment by neauoire** [comment]
I'm not particularly a fan of this idea, especially the parsing javascript code on the fly. I'm sure that if someone want to make their own operators, they can modify their library directly, it's simpler, safer and a lot more reliable. 

If someone has no programming knowledge and would like to use someone else's special operators, I think it would be a good opportunity to show this person how orca works underneath the hood and where to paste the operator code. I've had to do that in the paste and it was fun.

**Comment by ryanramage** [comment]
Ok sounds like solid logic. I will keep my own library of operators, and
try to share them via gists if others would be interested.
