### ISSUE TITLE
orca.keyOf tied to library keys 

### ISSUE THREAD

**Issue by ryanramage** [hundredrabbits/Orca#196]
With playing on #194 , I found that math and incrementing operators starting doing weird things. I realized the issue. 

```
return orca.keyOf(a + b)
```

is used to get the base 36 value of the operation. But in in the def of keyOf, it has the following

```
return uc === true ? this.keys[val % 36].toUpperCase() : this.keys[val % 36]

```

The problem is that this.keys is 

```
this.keys = Object.keys(library).slice(0, 36)
```

Can the library keys be disconnected from the keyOf function, and the keyOf function return a more traditional base 36 operation?

**Comment by ryanramage** [comment]
```
this.keys = '0123456789abcdefghijklmnopqrstuvwxyz'.split('')
```
that would solve it. Just locking it down. Would that cause any side issues?

**Comment by neauoire** [comment]
I don't think it would, but I'm just trying to understand what issue you're having, that might reveal some underlying issues somewhere else too.

**Comment by neauoire** [comment]
Implemented your change to `.keys` :) Otherwise it will use `.isAllowed` to check if that function exists in the library. Thanks!
