### ISSUE TITLE
Improved midi input selection UX

### ISSUE THREAD

**Issue by neauoire** [hundredrabbits/Orca#197]

**Comment by djbclark** [comment]
Does ORCA take MIDI inputs (e.g. using a MIDI dial to set variables in a selected range, or buttons to trigger an event)? I'm looking for a workflow where I set up the basics on a computer but then the actual performance gets done on MIDI devices easier to "play" than a computer keyboard. Sorry if this is a bad place to ask the question, but it is the top google result (and no others are useful so far), so answering it here will likely be useful to people other than myself. Thanks!

**Comment by djbclark** [comment]
Looking into this more, it seems the answer is "no", but that it could likely be BSed to some extent by using some macro program to output a specified "write" command on the MIDI controller keypress - or perhaps more cleanly, by writing a program that did this in interface with ORCA's UDP port, so UI focus wouldn't be an issue.

write:H;12;34 Writes glyph H, at 12,34(optional).

**Comment by neauoire** [comment]
Actually, for my own shows I do it. I write into the orca grid via UDP to convert the incoming midi knob changes.
There is other people doing similar things with MaxMSP on [here](https://llllllll.co/t/orca-livecoding-tool/17689).
