### ISSUE TITLE
How does 'b' work?

### ISSUE THREAD

**Issue by OrangeTux** [hundredrabbits/Orca#198]
I'm not sure if `b` is broken or I use it wrong.

As I understand `b` 'bounces' back and forth over a sequence which boundaries are given by the parameters of `b`. So the following example should output 1, 2, 3, 4, 5, 6, 7, 6, 5, 4, 3, 2, 1 and so on:

``` orca
1B7
.1.
```
Is my understanding of `b` correct?  If so, than `b` seem to be broken. The output of `b` doesn't change. Using Orca 0.7.1 on Ubuntu

**Comment by nlebellier** [comment]
Hi,

if your `B` is in capital it should work as you said. Otherwise you need to bang your b operator.

**Comment by neauoire** [comment]
You got it right, and it's not broken. 
I think the best way to understand how `B` works is to try and visualize the result, try:

```
7B4.
.3.X
```

If you change the first port, you'll notice that the `X` output goes back and forth. Alternatively, you can automate it with something like:

```
#.incr.#....#.clock.#
.....................
I8..........I8.......
6B4.........4B4......
.2.X.........0.X.....
```

**Comment by nlebellier** [comment]
well i clone the latest version under windows 10 and it seems to be stuck for me too. So @OrangeTux you may be right...

by the way, I always fight to find the number version of Orca. Why not display it obviously ?  
the shortcut is `cmd + r` right ?

**Comment by neauoire** [comment]
There is no menu for browser-version users and OSX users, but I could display the version number a few more frames.

**Comment by nlebellier** [comment]
Ok i miss the change of the b behaviour (the initials B.B.) but i must admit i don't catch how it works.

**Comment by neauoire** [comment]
It works just like before, but it takes a value as input, which can be a clock(`C8 in B4`) will work the same as before, or a `I8` if you don't want to sync with the clock.

**Comment by nlebellier** [comment]
ok but now the B operator needs a friend to work, before it was independent. So B "bounce" alone is just a substraction operator right in absolute value ? So the "bounce" name is quiet weird no ?

**Comment by neauoire** [comment]
It does need a friend to work now yes, how would you call it now? I'm not against renaming it. If you have a better name that starts with `B`, I'll take it :)

**Comment by nlebellier** [comment]
Well B as **Between** : returns the absolute value of the substraction between the two terms

**Comment by neauoire** [comment]
Perfect :) I like it!, would you like to add it yourself to library.js?

**Comment by nlebellier** [comment]
Done !

**Comment by neauoire** [comment]
thanks!

**Comment by OrangeTux** [comment]
Thanks for all the info!
