### ISSUE TITLE
open in the menu file sometimes does not work

### ISSUE THREAD

**Issue by nlebellier** [hundredrabbits/Orca#199]
The shortcut is always working but the open entry sometimes fails...

**Comment by neauoire** [comment]
yeah, the window needs an interaction before it's allowed to open a popup, if you touch the canvas, then use the menu, it should work.

**Comment by nlebellier** [comment]
exact !

**Comment by neauoire** [comment]
I'll leave this open as a personal note until I find a way to trigger an interaction with Electron.
