### ISSUE TITLE
The rate argument on the C operator does not work as intended

### ISSUE THREAD

**Issue by nilaykumar** [hundredrabbits/Orca#201]
The C operator is, at the moment, defined to output `orca.f % (mod * rate)`. This results in being unable to slow down the clock (and instead lengthening each cycle).

I believe (due to all the videos and tutorials I've seen) that what it should be returning is: `Math.floor(orca.f / rate) % mod`, which it used to be a few commits ago.

Note that these two are indeed different. Take, for example, f=50, rate=3, mod=5.
Is this the intended behavior?

**Comment by neauoire** [comment]
My bad, I accidentally injected this error in the last version.
I have just correct this :) Sorry.
