### ISSUE TITLE
web help

### ISSUE THREAD

**Issue by wraybowling** [hundredrabbits/Orca#203]
The web version of ORCA allows ? to be typed onto the grid instead of bringing up Help. Until other features work on the web version, accessing the list of things that do work via Help is pretty crucial.

**Comment by neauoire** [comment]
But the `?` operator is the [Pitch Bend](https://github.com/hundredrabbits/orca#io) operator, to display the guide, it has always been `c-G` to bring up the help.

**Comment by neauoire** [comment]
Use cmd+g to open the guide.

**Comment by wraybowling** [comment]
Sorry, I was coming from orca-c where `?` is the command for help. I should instead make a complaint over there about non-parity.
