### ISSUE TITLE
OBS window capture not working on Win10

### ISSUE THREAD

**Issue by brubsby** [hundredrabbits/Orca#205]
Saw in another issue it had something to do with hardware acceleration, but window capture isn't working for ORCA on OBS on Win10 for me. Here's a screenshot but I'm not sure how helpful it is: 
![orca window capture](https://user-images.githubusercontent.com/57653502/73038688-f3e17e00-3e18-11ea-8f9d-9d4b1de332ed.png)
(edited with better pic)

**Comment by neauoire** [comment]
I cannot replicate it, maybe OBS cannot screen cap the html5 canvas?
What happens if you try and record this: https://hundredrabbits.github.io/Orca/

**Comment by brubsby** [comment]
github.io orca doesn't seem to work for window capture either (although desktop capture with cropping does the job, but can't hide cursor among other things)
![image](https://user-images.githubusercontent.com/57653502/73038653-cf85a180-3e18-11ea-8709-c425c481622b.png)

**Comment by neauoire** [comment]
In this case, this is a OBS issue.

**Comment by nlebellier** [comment]
hi,

use an alternative software : Record Desktop Screen Capturer Recorder

https://github.com/rdp/screen-capture-recorder-to-video-windows-free/releases

it works for me video and audio with Orca sends midi to Helm

**Comment by brubsby** [comment]
did a little more investigation, seems like the browser version works in chrome with hardware acceleration disabled:
![image](https://user-images.githubusercontent.com/57653502/73097077-ec1ee980-3eab-11ea-90d9-b433e680a039.png)
although that's not optimal.

also someone said window capture worked on recent releases of firefox with hardware acceleration and i have found it does not
![image](https://user-images.githubusercontent.com/57653502/73097447-cba35f00-3eac-11ea-8ea1-7c957aeb7271.png)

however, like chrome, turning off hardware acceleration makes it work with window capture again:
![image](https://user-images.githubusercontent.com/57653502/73097613-348ad700-3ead-11ea-9658-9f7a4bbd86b5.png)

i realize the hardware acceleration on browsers not working in OBS is an OBS issue, but, just putting all this

**Comment by neauoire** [comment]
I think it's possible to disable it when you build the electron project, I've never tried it but I think it's part of the electron API :) You should give it a shot.

**Comment by tonijota** [comment]
IT's a known bug of Electron, not ORca itself. I have found a workaround for this, working in Windows 10. Right click on orca.exe, compatibility and check to run this program with compatibility for Windows 8. Then, add the source on OBS and orca will appear.
