### ISSUE TITLE
Can't find Loop command (or something similar)

### ISSUE THREAD

**Issue by rndD** [hundredrabbits/Orca#210]
Hi, thx for the nice tool!

As I can see from old videos and code history Orca had a Loop (L) command. Not L is Less.
What happened to the loop cmd? How can I achieve the same logic?

**Comment by rndD** [comment]
Is this still relevant https://github.com/hundredrabbits/Orca/blob/master/examples/basics/l.orca ?

**Comment by neauoire** [comment]
Ah yeah, I need to update the example, the L command has changed since.

If you really need the old interaction, you could do something like:

```
..C4..........
..2.4Qcafecafe
4Gfeca........
.feca.........
```

But it's quite destructive to write multiple cells that way, there might be a better way to do what you want using just a `T` operator.

**Comment by rndD** [comment]
`T`. Yeah, this perfectly fits.
Thank you!
