### ISSUE TITLE
Variables are not working across the whole project

### ISSUE THREAD

**Issue by sxiii** [hundredrabbits/Orca#213]
Hi.

I am getting really strange bug. I create a variable in the right part of the screen zone.

When I am trying to use it on the bottom of the workzone, it works. But when I move it to the top part of the workzone, it does not read the values.

It seems like the variables aren't consistently sent across the whole workbench. Very weird, maybe I am doing something wrong?

[variables-broken-on-the-right.orca.zip](https://github.com/hundredrabbits/Orca/files/4365584/variables-broken-on-the-right.orca.zip)

![image](https://user-images.githubusercontent.com/575925/77254650-a475cd80-6c62-11ea-9aa8-4b2fcb24ea1d.png)

**Comment by sxiii** [comment]
Already understood; variables are readable only on the rows after assignment. Is this intentional or a bug? :)

**Comment by neauoire** [comment]
It's intentional :)
