### ISSUE TITLE
Operators documentation too vague/short

### ISSUE THREAD

**Issue by Alberaan** [hundredrabbits/Orca#218]
Hi!

I often find that operator documentation could be improved or expanded. I would be nice to know where each of the inputs are located, a longuer explaination or even some examples.

**Comment by nlebellier** [comment]
have you looked here : 
https://github.com/hundredrabbits/Orca/tree/master/examples/basics

**Comment by Alberaan** [comment]
Hummm I hadn't had a look on those. But even after going through them (I have gone through some of them now), I whink it would be an improvement in the documentation to explain the position of each of the parameters at least...

**Comment by neauoire** [comment]
If you have suggestions for improvements in the operator descriptions you're welcome to edit [this file](https://github.com/hundredrabbits/Orca/blob/master/desktop/sources/scripts/core/library.js#L29), just make sure that the text description is less than 35 characters long.

**Comment by Alberaan** [comment]
Hummm maybe it would be possible to write it like this maybe?:
B subtract (a) (b): Outputs difference of inputs.

First parenthesis means inputs from the left, second right parameters. They could also be in their positions:

B operatorname (leftmostparameter 2leftmostparameter) (2rightmostparameter rightmostparameter)

**Comment by neauoire** [comment]
The guide is only there to help people discover each operator by giving simple hints of their usage, I don't think that by writing the port name in the operator definition it makes things clearer. The list of ports is available [here](https://github.com/hundredrabbits/orca#operators), but also by hovering a port you can see its name.

I think it would add clutter by duplicating their names in the operator definition. Maybe someone can come up with better definitions for some of the more complicated ports.

**Comment by onewheeltom** [comment]
I've been going through every operator in :
