### ISSUE TITLE
MIDI sync from external clock not working on Windows 

### ISSUE THREAD

**Issue by Simon-Claudius** [hundredrabbits/Orca#219]
Hey you lovely people,

I've been trying to sync Orca to Ableton Live via loopMIDI, without much luck. Syncing Live to Orca with Orca providing the clock works, but the other way round (which is what I want to do) doesn't yield any results. I double checked all MIDI assignment in Live and Orca, but it appears to me as though Orca just isn't listening - unless this is user error (which I hope since it'd be an easy fix). Is there a guide or example video somewhere out there for this particular setup. I couldn't find too much on the topic. Is this a known issue?

Any help would be appreciated. I'd love to incorporate Orca into my setup.

Take care of yourselves and stay safe,
Simon-Claudius

**Comment by unthingable** [comment]
FWIW I haven't been able to get Orca to sync to Bitwig on a OSX either (yet, at least), and I'm fairly certain the clock is being sent to Orca.

**Comment by neauoire** [comment]
Orca doesn't support Midi Clock, I don't know how to implement it properly.

**Comment by unthingable** [comment]
Did it ever? I see reports from people getting it to work, like https://llllllll.co/t/orca-livecoding-tool/17689/520.

**Comment by neauoire** [comment]
Yeah I did a few attempts at implementing it, it would work for some people but not everyone, and didn't work reliably, once I did a show and it stopped working suddenly and I couldn't figure out why, so I took it off. Nowadays I just sync with UDP instead.

**Comment by unthingable** [comment]
I see. That seems drastic, especially if it worked for some :) 

Well now there is #240, looks like it's on track to getting it working again, with a simple fix.

This is an amusing line of thinking: "I can probably get Bitwig to send UDP" -> "maybe it's simpler with a helper process to translate clock/OSC to UDP (like others are doing with Max)" -> "if I can do this in another process, why not in Orca". I was curious what other problems there were, the implementation I saw in code looked straightforward and correct (count the pulses and `update`). The only other thing I could think of was `tap` getting called too often in the main thread.
