### ISSUE TITLE
Unable to resize/manage window on Windows 10

### ISSUE THREAD

**Issue by Gadgetoid** [hundredrabbits/Orca#22]
There's no Window chrome in Windows 10, so I can't scale the window to match the work area size. It's also apparently not showing up in Alt+TAB.

It's possible to resize by opening the Terminal and grabbing the bottom right corner, but it's a bit of a hack.

Also the GUIDE.md link is broken - https://github.com/hundredrabbits/Orca/blob/master/GUIDE.md

**Comment by neauoire** [comment]
- Removed the broken link
- Added chrome to Windows build,

Could you pull again and see if that works?

**Comment by neauoire** [comment]
Could I close this?

**Comment by Gadgetoid** [comment]
Aye, sure thing! Thank you.
