### ISSUE TITLE
Re-introducing the graphic feature

### ISSUE THREAD

**Issue by MLK97** [hundredrabbits/Orca#227]
I found an issue from almost a year ago #151 where the graphic extension is discussed.
However, it has been removed since then from the commander.js.
I couldn't find the version when this was changed, but I would be very interested in seeing it reintroduced.
Is anything planned in this regard?

**Comment by neauoire** [comment]
Not really, it was complexifying the project too much so I took it off. It's best to use a translucent window overlay instead. I have no plans to bring it back, if you really need this feature, I recommend asking on the lines forum how different people achieve this in their videos.
