### ISSUE TITLE
Name collision

### ISSUE THREAD

**Issue by da4089** [hundredrabbits/Orca#228]
The name of this project has an unfortunate collision with Henri Bal's "Orca" language.

See in particular the book "Programming Distributed Systems", but also a range of papers especially from  Vrije Universiteit Amsterdam.

**Comment by da4089** [comment]
Henri's home page https://www.vuhpdc.net/henri-bal/

**Comment by neauoire** [comment]
I have never heard of thi project, but Orca most often collide with the screen reader with the same name.

**Comment by da4089** [comment]
I was less concerned about the screen reader, since it's a different class of project (screen reader vs. language).  But I thought you should know that there was an existing, and somewhat well-known language of the same name.

**Comment by rookie212** [comment]
Orca reader was downloaded when i tried to install on Ubuntu terminal. By the way I could not run Orca and Pilot with Ubuntu system. Are there any command to download them from terminal? Ps: I am really new on the Ubuntu.

**Comment by PlaidDroid** [comment]
> Orca reader was downloaded when i tried to install on Ubuntu terminal. By the way I could not run Orca and Pilot with Ubuntu system. Are there any command to download them from terminal? Ps: I am really new on the Ubuntu.

Even I had tried searching and found it out to be a screen reader :laughing:. You cannot use `apt` to download. You can use pre-built from https://hundredrabbits.itch.io/orca or, can build yourself.

**Comment by rookie212** [comment]
So it does not work on Linux!

**Comment by neauoire** [comment]
It works on linux, but use the sources, not apt-get.
If you are on Arch, use the xxiivv-orca package for the C version, otherwise just clone this repo and build.
