### ISSUE TITLE
error in "colors.orca" example

### ISSUE THREAD

**Issue by onewheeltom** [hundredrabbits/Orca#234]
Variables are named r, g and c (should be b), so when the generator tries to write "rgb", the b value is empty, so a null value gets written to the 

Change line 5 from 
.rV2.gV1.cVf....
to
.rV2.gV1.bVf....

**Comment by neauoire** [comment]
Thanks, fixed it [here](https://git.sr.ht/~rabbits/orca-examples/tree/master/misc/colors.orca).
