### ISSUE TITLE
Strange T behavior

### ISSUE THREAD

**Issue by unthingable** [hundredrabbits/Orca#235]
Using current `master`, this plays as expected:

```
.C............
.08T.**..***..
....:01Da.....
```

However, if the first step of `T` is a `*` then all remaining steps play as `*` regardless of what's in them. I.e.,

```
...............
..C............
..58T*.....**..
.....:01Da.....
```

plays the same as

```
...............
..C............
..58T********..
.....:01Da.....
```

Bug or I am holding it wrong?

**Comment by unthingable** [comment]
More strangeness:

This just writes a `E` that does not move:

```
..............
..C..HHHHHHHH.
..48TEEEEEEEE.
...XE.........
...E..........
```

This initially writes moving `E`s every 8 frames.

```
..............
..C..HHHHHHHH.
..48TEEEEEEEE.
...xE.........
...E..........
```

Why not every frame? And then, after messing around with the steps it stops writing altogether. For example, deleting the first `E` step (`T.EEEEEEE`) stops writing, putting it back does not restore it. Changing `x` to `X` does nothing, changing `X` to `x` writes a single moving `E`.

**Comment by neauoire** [comment]
> However, if the first step of T is a * then all remaining steps play as * regardless of what's in them. I.e.,

That's because there is a `*` right above the `:` meaning that it bangs, which is somewhat working as expected. Commented and locked `*` are also read as bangs.

Just do this instead:

```
C...........
28T*.....**.
............
..:01Da.....
```

**Comment by neauoire** [comment]
> This just writes a E that does not move:

That's because the `X` is locking the `E` and stopping it from moving.

Try something like this instead:

```
...D.8C3....
4.X...13TSWE
.......xW...
```

**Comment by unthingable** [comment]
> there is a * right above the : meaning that it bangs

Got it. It was strange to me as I thought `T` would "bind" its arguments preventing them from "acting" in other ways (old conventional programmer habits, still new at this), didn't even occur that `:` would also get banged by a nearby `*`. It makes sense now, that is neat!

Thank you for the explanations.

**Comment by neauoire** [comment]
No problem, let me know if you have any more question :)
