### ISSUE TITLE
Where is the "examples" folder?

### ISSUE THREAD

**Issue by onewheeltom** [hundredrabbits/Orca#238]
It appears to be missing. Plus all the folders inside : basics, misc, setup, etc

**Comment by neauoire** [comment]
The links should all be pointing to this [repo](https://git.sr.ht/~rabbits/orca-examples/tree). 
Did you find a broken link?

**Comment by unthingable** [comment]
It was removed (cb672d6af5f588e448c1e8853289721d36e4623e) and I too wondered why. Was very useful to have.

**Comment by neauoire** [comment]
I had to maintain the examples in the various repos for the various versions of Orca and I was tired of having to replicate changes everywhere. Now they are all collected at the same place, it makes it easier for me to manage, also making changes to the examples shouldn't impact the source code of the javascript repo anymore.

**Comment by onewheeltom** [comment]
I  just went back to where the examples were in GitHub and they were gone. Only maintaining one copy makes total sense, though. Perhaps leave some pointers in the old hierarchy that point to the new location.

**Comment by unthingable** [comment]
Could it have been a git submodule?

**Comment by onewheeltom** [comment]
Folders in Orca/resources. Once I know where something is, I don't normally navigate through the web because I would have to scroll down to get to the link that would normally be near the top. If a[ GitHub Pages ](https://pages.github.com) link was the forward facing view of Orca content, then the folder structure would be hidden until clicking a link. Here is one of my GitHub Pages informational sites : [](https://onewheeltom.github.io/gameboy_camera/)
