### ISSUE TITLE
Midi slows pretty significantly when moving around after.. 

### ISSUE THREAD

**Issue by sense-amr** [hundredrabbits/Orca#24]
After you are running quite a few midi out objects.. (and this could very well be down to my poor coding and layout) .. overloading things.. i noticed midi gets pretty sluggish when moving the cursor reasonably quickly to get around to another place in the map .. in musical timing.. to keep the flow going.. 

I am using Windows 10 .. windows Build of Orca..  / Loopmidi ..

wondering if there was any way of improving this latency as it really is sometimes interfering with the flow of the jam im doing in orca.. .. would be great if it could be improved somehow .. 

But i just have to say .. Orca is an extremely enjoyable way to make music .. and thank you so much for making it .. 
much respect..

Sense

**Comment by sense-amr** [comment]
Also if you could please advise on how to go about Syncing ORCA with a daw? ..

**Comment by neauoire** [comment]
Fixed :) Give the new version a try, let me know if that's better for you.

**Comment by sense-amr** [comment]
Where is the exe?   file

**Comment by neauoire** [comment]
Just get it from Itchio, or pull this repo again :)
