### ISSUE TITLE
FR: deferred entry mode?

### ISSUE THREAD

**Issue by unthingable** [hundredrabbits/Orca#244]
All this talk about synchronizing things with duration-based Z got me thinking about ways of making simultaneous edits, and culminated in a mode I'll call "deferred entry".

* CmdOrCtrl+E: toggles deferred entry
* Edits made during deferred entry are kept in a separate buffer
* Buffer flashes periodically on and off, current edits are colored differently, so that you can see and compare
* Updated target indicators for X, O, etc. are also shown
* `Enter` commits, `Esc` or quitting deferred entry abandons

Use cases:

* Cue up multiple edits: change values, comment/uncomment things, drag blocks, etc.; then execute at once
* Preview offset changes for random access operators (X/O/etc.). I'm bad at geometry and keep guessing wrong offsets with disastrously fun results.

Suitable for mainline Orca? I could try an implementation, not sure I'm up to the challenge of messing with UI on this level.

**Comment by neauoire** [comment]
Too complex for mainline Orca sorry, I tried my hand at implementing it and it quickly grew into a freakish monster.
