### ISSUE TITLE
Tutorial at https://git.sr.ht/~rabbits/orca-examples has a mistake

### ISSUE THREAD

**Issue by onewheeltom** [hundredrabbits/Orca#249]
The last command in the tutorial at https://git.sr.ht/~rabbits/orca-examples defines "B" as bounce.
Wasn't sure how else to report this.

**Comment by neauoire** [comment]
Anywhere is fine, I will fix this :)
https://todo.sr.ht/~rabbits/orca/1

**Comment by neauoire** [comment]
Fixed :)
