### ISSUE TITLE
Orca as a tool to for the blind & visually impaired?

### ISSUE THREAD

**Issue by EstevanBR** [hundredrabbits/Orca#25]
I have a friend who works with blind and visually impaired students. He's been wanting to teach them coding & he is thinking he will learn python to teach his students python.

With technology like 3D printing, he has been able to teach blind/low vision students how to write their own name. Something we take for granted.

But then it got me thinking.. While ORCA is a very visual experience: What would it take to get it to output to some sort of Braille display?

I think that ORCA's visual strengths would translate very well into a tactile environment.

p.s. funny coincidence: https://www.linuxjournal.com/magazine/orcamdashtake-killer-whale-ride

Doing some research, it seems that full page braille displays are not affordable _yet_, but even a 1 line display might be a _good-for-now_ option.

**Comment by cancel** [comment]
I can make a braille-preferential mode for orca-c https://github.com/hundredrabbits/Orca-c if you can tell me what you need for it. orca-c uses a TTY instead of a web browser to display text, so you would need only some kind of braille display that can read from a virtual terminal, which i'm sure must exist.

**Comment by neauoire** [comment]
I don't think this should be part of `/master`, but a fork would be welcome.
The C port is definitely a better usecase for this.

**Comment by neauoire** [comment]
Is this what you had in mind?
https://www.youtube.com/watch?v=UQMCkfarzrw
