### ISSUE TITLE
Ableton Link?

### ISSUE THREAD

**Issue by iTerentius** [hundredrabbits/Orca#256]
Sorry if this has been brought up before. Not an issue but a feature request... I'd love to use Orca, Bitwig and Supercollider together. Ableton Link as a sync method would be glorious. Both Bitwig and SC can use Link. Were I a better programmer, I'd try and contribute, but I don't think that will happen. Just wondering if there are any plans for this?

**Comment by neauoire** [comment]
You can grab it here: https://github.com/hundredrabbits/Orca/pull/247

**Comment by iTerentius** [comment]
Thanks @neauoire!
