### ISSUE TITLE
add quick guide for controlling a soft synth with orca

### ISSUE THREAD

**Issue by lcb931023** [hundredrabbits/Orca#26]
It would be great if people who found orca can very quickly start making sounds with it. 

I saw there's some work getting started at #20 + Pilot. In addition to our toy synth, what do you think about having some helpful links for linking Orca with common soft synths? For me it took a while to search the net and figure out how to set up Orca => Midi => SuperCollider.

Links that were helpful to me: [A guide about enabling IAC Driver](https://feelyoursound.com/setup-midi-os-x/), and [SuperCollider's `MIDIIn` example](http://doc.sccode.org/Guides/UsingMIDI.html).

**Comment by neauoire** [comment]
Have you had a look at [Tutorial.md](https://github.com/hundredrabbits/Orca/blob/master/TUTORIAL.md)? You could append what you think is missing to that page :)

**Comment by lcb931023** [comment]
wow great, that's what I'm looking for 👍
