### ISSUE TITLE
Web version down?

### ISSUE THREAD

**Issue by mrdoob** [hundredrabbits/Orca#265]
Seems like https://hundredrabbits.github.io/Orca no longer works... 🤔

**Comment by neauoire** [comment]
https://hundredrabbits.github.io/Orca/ works for me? Is it because it's missing a `/` at the end?

**Comment by mrdoob** [comment]
Strange. It's working now...

**Comment by neauoire** [comment]
I renamed the `master` branch to `main` last night, I think it momentarily broke the gitpages :) I re-saved the page settings and it worked.

**Comment by mrdoob** [comment]
Ah! Maybe that was it.
