### ISSUE TITLE
Arbitrary files overwrite

### ISSUE THREAD

**Issue by vvzen** [hundredrabbits/Orca#27]
Hi guys!
Just checking this very nice project.
While trying to build using npm, a high severity bug alert popped up:

<img width="825" alt="screenshot 2019-02-06 at 08 17 25" src="https://user-images.githubusercontent.com/10340139/52326079-af7e8780-29e7-11e9-9755-c26d60c499ba.png">

Is this dependency going to be updated so that we can sleep safe and sound? 😀

**Comment by neauoire** [comment]
Fixed :)

**Comment by neauoire** [comment]
Fixed :)
