### ISSUE TITLE
Should reading `#` uncomment/unlock following characters?

### ISSUE THREAD

**Issue by eethann** [hundredrabbits/Orca#282]
I've seen this behavior in both orca-c and orca electron, seems like it might be a bug to me, but not sure if it's intended: reading a cell with `#` in it via `Q` or `O` seems to uncomment the following characters. I suspect this is an issue of the # being unlocked or some such but haven't delved into it. It can be a bit of a gremlin as a whole sequence can get messed up with a lot of `C`s and `A`s in it if you get an offset wrong.

Is this intended behavior?

**Comment by neauoire** [comment]
Oh! you're right, that is a bug.
I'll look int it :)

**Comment by eethann** [comment]
The only slight generalization would be to define a set of "unlockable" operators and check for them in the orca.lock or operator.lock. Then that gets to thinking about the other troublemakers: halted `;`s with capital letter note names after, etc. and those you wouldn't want to exempt from locking because they need to be commentable.

I suppose the only deeper potential fix would be to use a different mechanism for commenting, not locking. But that would be a deep refactor probably, and wouldn't handle all the other similar cases.

**Comment by neauoire** [comment]
I think I like the idea that `#` comments can be locked, I might even use that now that you've raised this issue to toggle commented blocks of code on/off. I don't think this is an issue in that case, it's more like a quirk of Orca's design, I'm not too keen on implementing a new layer of locking permissions on operators.

**Comment by eethann** [comment]
:)
