### ISSUE TITLE
Add support for MIDI CC

### ISSUE THREAD

**Issue by pierluigi** [hundredrabbits/Orca#29]
Hi there – what a great little project ⭐️ 

Any plans to add support for [MIDI CC](https://www.midi.org/specifications/item/table-1-summary-of-midi-message#3) events? Would be amazing. 

It could be something like adding [a new method here](https://github.com/hundredrabbits/Orca/blob/master/desktop/sources/scripts/io.midi.js#L117-L119) such as

```
function convertCC (control, value) {
 // return the data 
}
```

and creating a new MIDI_CC operator (or [extending the existing one](https://github.com/hundredrabbits/Orca/blob/master/desktop/core/library/_midi.js)) with a new operator with the following signature:

```
? . . . .
# ? -> new "MIDI CC" operator 
# . MIDI CHANNEL 0-F
# . MIDI CC MSB 0-F
# . MIDI CC LSB 0-F
# . VALUE LSB
# . VALUE MSB

# Example for Chan 0, Cutoff (CC 19) value 0 
? 0 1 3 0 0
```

**Comment by hamstah** [comment]
Hey @pierluigi you should have a look at my fork while @neauoire is away, I have midi CC in it.
https://github.com/hamstah/Orca/releases

In the release branch

**Comment by neauoire** [comment]
I've thought about it, but I feel like this would be better left to the user to parse for themselves via UDP messages.

**Comment by neauoire** [comment]
Added!
