### ISSUE TITLE
Allow midi command to chose port

### ISSUE THREAD

**Issue by josefnpat** [hundredrabbits/Orca#30]
I am using a synth called [helm](https://tytel.org/helm/) and it unfortunately does not have the ability to [filter MIDI channels](https://github.com/mtytel/helm/issues/50).

I would like to request that an additional operand to the `:` command be added for the port, so that I can set up two virtual midi ports, and route them to the individual helm synths.

I imagine this would be very nice feature for folks that have multiple analog devices.

**Comment by neauoire** [comment]
That would complexify the midi node for everyone who don't, but I get the idea.
I'll see if I can't find a solution that doesn't require adding a new input to the operator.
Maybe using UDP in the meantime would be better.

**Comment by josefnpat** [comment]
Thanks!

**Comment by neauoire** [comment]
After looking into this issue, I think it would be best to use a third party application to handle this.
