### ISSUE TITLE
Tabs for multiple songs? 

### ISSUE THREAD

**Issue by sense-amr** [hundredrabbits/Orca#34]
Just played the TOPLAP15 thing.. and it struck me that it was really difficult to transition between songs .. i had to make the one i will play next be on an inactive midi channel in order for it to play nothing.. then arm it for daw sync after.. when i wanted to play it .. 

I was thinking with @nobodycarestrue that it would be great to have tabs where we could load and have ready separate orca songs.. with a way of making the ones not playing have all the correct settings ie for me loopmidi sync enabled and ready to go .. but to have it "turned off" i guess? untill ready to play it ? .. any ideas? .. @hamstah @neauoire ?

**Comment by neauoire** [comment]
I've done some experiments with this in the past. 
I'm for this to be part of Orca, I'll try to implement a basic version of this soon!

**Comment by neauoire** [comment]
While I cannot implement this feature right now, I think I might try to allow layers in a song so different part of a file can be isolated and ran individually.

**Comment by neauoire** [comment]
Implemented [project mode](https://github.com/hundredrabbits/Orca#project-mode).
