### ISSUE TITLE
maybe T is slow?

### ISSUE THREAD

**Issue by nobodycarestrue** [hundredrabbits/Orca#38]
```
......D1.................
......*..................
.....1cg.123456789abcdefg
..Dg..0gT*...............
aV*...bV.................
.........................
.........................
.........................
...Va.Vb.................
.........................
```

I probably won't explain this clearly, but to bring to your attention, for a while I thought C and D were slightly off by 1 frame (or something).  If you notice with the example above, when 1cg clocks a gT* (even when c is banged with a D1) and compared to just a regular Dg, Dg will bang at the 0 while T is outputting a frame behind. Always thought this lag was because of C being slow, but now seeing 1cg output a 0 in sync with Dg's bang, makes me think T is the slow one?

**Comment by neauoire** [comment]
I have updated `D` to sync with `C`, let me have a look at `T` as well.

**Comment by neauoire** [comment]
Fixed :)
