### ISSUE TITLE
Send Midi Clock 

### ISSUE THREAD

**Issue by neauoire** [hundredrabbits/Orca#39]
It would be nice if Orca sent midi clock out.

**Comment by neauoire** [comment]
cc @hamstah

**Comment by hamstah** [comment]
You need to get 24 pulses per quarter note, so we need to make the clock interval much shorter and update only every 6 pulses (like the midi clock in). Not sure how precise the js interval clock is going to be at that resolution, but should be reasonably simple to add.

**Comment by ryanramage** [comment]
@hamstah could you have a look at my branch? I think I got it mostly working, adding the needed precision fo the 24 ppqn. But I might have slowed the orca clock. Anyway I get hardware sync now. But I really need other eyes on this ;)

**Comment by nai888** [comment]
Hey! Is there any documentation on how to send the midi clock?
