### ISSUE TITLE
Bug with new V when using banged V in K 

### ISSUE THREAD

**Issue by sense-amr** [hundredrabbits/Orca#43]
This is a bug i discovered after i started using Banged V's inside a K .. 
my setup is this .. 

![image](https://user-images.githubusercontent.com/1504019/53629612-151a0880-3c62-11e9-91c0-beab33625f3e.png)

....................................................................................
....................................................................................
....................................................................................
..........................1D4.......................................................
.........................xV.........................................................   
.................................................................................... <---inserting a V here will make `:34c` magically dissapear!
...............................8Kx..................................................
..................................:34c..............................................
....................................................................................
....................................................................................
....................................................................................
....................................................................................
.............................................................

When inserting a new V above the K .. orca responds by removing the `:` object.. 

video is here.. 

[ydidVkillit.zip](https://github.com/hundredrabbits/Orca/files/2918824/ydidVkillit.zip)
despite using the UDP commands in this video example .. i found it still occurs with just normal ie ,non udp operation .. 

Incidentally the error doesnt happen if you insert the new V below the K ..

**Comment by neauoire** [comment]
Pushed a little update that, I believe, fixes that.
Could you double check?

Also, to post code on GitHub, you need to use backtick`.

**Comment by sense-amr** [comment]
sure can check .. ..
you wanted me to backtick the whole .orca text?:)
