### ISSUE TITLE
Song repo

### ISSUE THREAD

**Issue by ryanramage** [hundredrabbits/Orca#44]
It would be amazing to have a (folder, wiki, repo) of songs that people have created and would be willing to donate.  I've seen some amazing ones on twitter, and it would be nice to have the src to play around with. 

A lot of times when I am writing code for projects I need some quick .orca files that produce something nice. I really appreciate the popcorn.orca file, but grow weary of it 😢

**Comment by ryanramage** [comment]
I guess I would suggest separating orca files into maybe 3 categories

 1. Test - used for performance testing or operator testing
 2. Examples - used for tutorials or teaching operators
 3. 'Songs'.  Something more full - maybe not a song in the traditional sense, but can load and go?

**Comment by neauoire** [comment]
I would do `examples/projects` for application specific/tutorials resources, and `examples/sequencers` for various general purpose sequencers? What do you think?

**Comment by theatlasroom** [comment]
Hey, just noticed this discussion, what do you think of [https://patchstorage.com](patchstorage.com) as an option? I'm not sure how you go about adding a new platform, though i suppose someone in the discord would know.

**Comment by nobodycarestrue** [comment]
> Hey, just noticed this discussion, what do you think of [patchstorage.com](https://patchstorage.com) as an option? I'm not sure how you go about adding a new platform, though i suppose someone in the discord would know.

I've brought patchstorage.com up also to neauoire and think it would be the best place for orca patches. There's an email here (hello@patchstorage.com) to contact to ask if Orca can be added as a platform: https://patchstorage.com/privacy-policy/

**Comment by neauoire** [comment]
Go on ahead with this if you need.

**Comment by nobodycarestrue** [comment]
Should probably take a vote in chat or something. This was recently brought up and it seemed like most wanted to create a central GitHub spot because most pull things/update through command line.

**Comment by okyeron** [comment]
New orca user here with opinions:

- Many music people wont want to deal with using github to grab a patch or two.
- The idea being to open access up to **Everyone** - not just people in the chatroom or those using git, etc.
- I'd like an easy way to scan through user patches with a nice description of what it does
- patchstorage is a very good solution for this.
- patches could be any combination of songs/examples/tests/wip/etc.

As an example, I'm active with the monome/norns community and the newb-ness with using github for sharing is a HUGE hurdle for many users. 

So here's a +1 for patchstorage

**Comment by neauoire** [comment]
I don't want to manage this, if someone can take the reigns on this one, you've got my full support and I'll make sure this is visible and accessible. :)

**Comment by neauoire** [comment]
Thanks to @okyeron, Orca is now whitelisted on [patchstorage](https://patchstorage.com/platform/orca/), you can upload them [here](https://patchstorage.com/upload-a-patch/).
