### ISSUE TITLE
Reopen last open orca file

### ISSUE THREAD

**Issue by ryanramage** [hundredrabbits/Orca#47]
A lot of editors, when you exit and reopen them, will open the last file(s). I think this would be consistent with user expectations.

**Comment by neauoire** [comment]
Good idea :) Will implement!

**Comment by neauoire** [comment]
Done.

**Comment by neauoire** [comment]
<img width="439" alt="screen shot 2019-03-07 at 9 05 23 am" src="https://user-images.githubusercontent.com/1455726/53922557-36428500-40b8-11e9-8e8c-7af54dda3428.png">

Click resume to open last active file :)

**Comment by ryanramage** [comment]
Thanks! This is great.
