### ISSUE TITLE
BPM is not preserved when .orca file is opened

### ISSUE THREAD

**Issue by ryanramage** [hundredrabbits/Orca#48]
Changing the bpm should be associated with the orca file I think.

**Comment by neauoire** [comment]
I don't think it should. 
But if you want to preserve the BPM of an orca file, you can do something like this:

```
.......
.S.....
.;b100.
.......
```

**Comment by ryanramage** [comment]
oh neat trick. maybe good to add to the readme.

**Comment by neauoire** [comment]
It's a good idea, I'll at least add an example.
