### ISSUE TITLE
possible Note Length fix?

### ISSUE THREAD

**Issue by nobodycarestrue** [hundredrabbits/Orca#49]
in the io.midi.js file, the convertLength section should be replaced with something like:

```
  function convertLength (val, bpm) {
    // TODO get bpm from daw midi
    if (!bpm) {
      bpm = 120
    }
    return (60000 / bpm) * (val  / (bpm / 32) )
  }
```

this brings note lengths closer to 1 = 1/16th and f = 16/16

<img width="970" alt="screen shot 2019-03-06 at 8 15 00 pm" src="https://user-images.githubusercontent.com/47595933/53933250-47f14180-4052-11e9-9f6d-26f3f9273632.png">

here is an example of 120 bpm displaying 1 - f (bottom to top) values when the code is replaced with the above.

this also only works for 120 bpm (not sure how to get orca's current bpm to be read as the bpm in the io.midi.js).

you can still notice that the lengths aren't perfect though and maybe needs some fine tuning, especially when notes overlap more problems arise. 

maybe headed in the right direction though. :-)

**Comment by sense-amr** [comment]
io.midi.js id imagine ?

**Comment by nobodycarestrue** [comment]
better way can also just change `60000` to `240000` for 120 bpm only and `15` to `16`

equation to take bpm would be: ( (bpm * 2000) / bpm) * (val / 16)

**Comment by nobodycarestrue** [comment]
<img width="861" alt="Screen Shot 2019-03-10 at 12 48 04 AM" src="https://user-images.githubusercontent.com/47595933/54082749-5ac47a00-42cf-11e9-9b16-ee966164369f.png">

**Comment by sense-amr** [comment]
ahh yeah but it also has to be calculated on the actual BPM .. which as we know can be ever changing .. so it has to get that value from the sync of the daw .. which is essentially what hamstah made it do .. to enable midi sync.. so if that value could be dynamically used in calculating note length that would be usefull.. something like a VAR for midi sync bpm would work .. ironcailly we could do it in orca.. not so much in code for orca tho

**Comment by nobodycarestrue** [comment]
100%, still have to manually change bpm value (not smart enough to figure out where to get the bpm value from).  at least 16 evenly spaced lengths from `1` to `g` now. :-)

**Comment by sense-amr** [comment]
at fixed bpm :)
![image](https://user-images.githubusercontent.com/1504019/54083073-1ee2f080-4373-11e9-9dd8-b435762e5e4b.png)

**Comment by nobodycarestrue** [comment]
how did you do it?

**Comment by neauoire** [comment]
Do you want to make a PR?

**Comment by nobodycarestrue** [comment]
If you could make a PR that would be awesome. :-)

For some reason, that option is greyed out for me.

**Comment by sense-amr** [comment]
@nobodycarestrue https://github.com/hundredrabbits/Orca/pulls

**Comment by nobodycarestrue** [comment]
> @nobodycarestrue https://github.com/hundredrabbits/Orca/pulls

I know this, "create pull request" is greyed out for me.

**Comment by sense-amr** [comment]
not sure what you mean man.. anyone can create a PR ..

**Comment by neauoire** [comment]
You don't have writing access to the core repo, you must first make a fork :) And you make a PR form that fork.

**Comment by sense-amr** [comment]
ahh ok .. so i guess thats the procedure here..

**Comment by neauoire** [comment]
Conversation moved [here](https://github.com/hundredrabbits/Orca/issues/49).
