### ISSUE TITLE
When writing with UDP's w, the letter should be locked

### ISSUE THREAD

**Issue by sense-amr** [hundredrabbits/Orca#50]
After the latest fix from a git pull of the master.. 

Updating 3c34858..ba3bb7c
Fast-forward
 desktop/core/library/c.js           |  2 +-
 desktop/core/library/d.js           |  6 +--
 desktop/core/library/g.js           | 24 +++--------
 desktop/core/library/o.js           |  7 ++--
 desktop/core/library/p.js           | 17 ++++----
 desktop/core/library/q.js           | 27 ++++---------
 desktop/core/library/t.js           | 21 +++++-----
 desktop/core/library/x.js           |  7 ++--
 desktop/core/operator.js            |  5 ++-
 desktop/core/orca.js                |  4 +-
 desktop/main.js                     |  4 +-
 desktop/sources/index.html          |  6 ++-
 desktop/sources/scripts/source.js   | 79 +++++++++++++++++++++++++++----------
 desktop/sources/scripts/terminal.js |  8 +++-
 examples/benchmark.orca             | 12 +++---
 examples/read+write.orca            | 19 ++++-----
 examples/udp+loop.orca              | 15 +++++++
 17 files changed, 152 insertions(+), 111 deletions(-)
 create mode 100644 examples/udp+loop.orca

I have noticed the following..

1. Inside a T Capital objects populate as operators.. 
2. Capital objects into V from T populate as objects when udp written ..;w .. 

```...1D1...........
..1V*............
......V1.........
......*..........
.....1c8.........
.....178TABDFG...
......nV.........
.................
.................
...V1.Vn.........
...*;w.12:11.....
............G....```

**Comment by sense-amr** [comment]
ill test now with latest pull.. 
then close..

**Comment by sense-amr** [comment]
not closed yet as .. 

```1C8.........
.38TADEFDFGE
.1VF........
............
............
............
............
............
.1D2.V1.....
...;wF16:13.```

shows that Operators populate from ;w object that come from T which are capital .. eg. E G F GA etc .

**Comment by sense-amr** [comment]
hmm fix is that when connected to a "use case" or operator that will use the written object.. it will then be "locked" as a value and not as an operator ..

**Comment by neauoire** [comment]
After some thought, I think the output of the UDP should be non-locking.
