### ISSUE TITLE
Q in latest update no longer grabs multiple object with "length"

### ISSUE THREAD

**Issue by sense-amr** [hundredrabbits/Orca#51]
In the last update of the master where several core operator objects were replaced..
I have discovered Q no longer functions as expected..

Before the update 4Q would result in a Query length of 4  . . . . which we could then move around with X and Y parameters.. which then grabbed multiple objects in a line.. like the example code below shows.. 

```....I38.....
1D1.54Q.....
.*;f346.....
............
......#f456#
......#f346#
......#f453#
......#f246#
......#r...#

```

Since the update the Length of the Query object seems not to correspond to the length of the query itself .. but rather an Offset value to the query with a length of only 1.. 

```
1D1.54Q.....
.*;...3.....
............
......#f456#
......#f346#
......#f453#
......#f246#
......#r...#
```

**Comment by nobodycarestrue** [comment]
Can confirm that `Q` is broken as well as `P`. :-(

**Comment by sense-amr** [comment]
i dont remember what P was supposed to do .. so i have no idea about the changes.. but i have referenced in this issue the changes in Q that i have observed.. since the cleanup of operators.. patch ..

**Comment by neauoire** [comment]
On it.

**Comment by neauoire** [comment]
@nobodycarestrue `P` is working fine for me?

```
........
.C4.C4..
.04P0...
...0123.
........
```

**Comment by neauoire** [comment]
Fixed issue with `Q` and improved the `/read+write` example to better demonstrate each usecases.

```
...............................2C4.......
.#.READ.#.......................34T0246..
................................lV6......
.C8...........Cg...........Vl............
.70O01234567..78T01234567..602Q01234567..
...7............7............67..........
.........................................
.#.WRITE.#.....................Vl........
...............................6.Vl......
.C8.C8........Cg.C8........Vl2.JA61......
.70X7.........78P7.........602G67........
...01234567.....01234567......01234567...
.........................................
.........................................
.........................................
.........................................
.........................................
```
