### ISSUE TITLE
P breaks anything to its right

### ISSUE THREAD

**Issue by nobodycarestrue** [hundredrabbits/Orca#54]
It's not so much that `P` is broken, it's that it breaks any operator to the right of it that is caught in it's upper `P-len`.

<img width="548" alt="Screen Shot 2019-03-15 at 3 01 05 PM" src="https://user-images.githubusercontent.com/47595933/54464337-8910e200-4733-11e9-9c43-e1826be08f70.png">

**Comment by neauoire** [comment]
Fixed :)
