### ISSUE TITLE
Notes canceling each other bug

### ISSUE THREAD

**Issue by nobodycarestrue** [hundredrabbits/Orca#59]
So now with one bar note lengths, I'm sure some have noticed that some notes have been cancelling each other out. (This bug has always been there but was less noticeable with the shorter note length max.) 

I've been using my note length test to try to figure this out and unfortunately there is no way to consistently recreate the issue. It seems to be semi-random? 

All I for sure know is that if a note is retriggered while still playing, there is a possibility of it cancelling out the next note(s) played after.

Here's the test with the results to follow:
```
aVg................................
...................................
..Va.......Va.......Va.......Va....
.Dg.......Dg.......Dg.......Dg.....
..:01Cw1...:01Ew5...:01gw9...:02Cwd
..Va.......Va.......Va.......Va....
.Dg.......Dg.......Dg.......Dg.....
..:01cw2...:01Fw6...:01Awa...:02cwe
..Va.......Va.......Va.......Va....
.Dg.......Dg.......Dg.......Dg.....
..:01Dw3...:01fw7...:01awb...:02Dwf
..Va.......Va.......Va.......Va....
.Dg.......Dg.......Dg.......Dg.....
..:01dw4...:01Gw8...:01Bwc...:02dwg
```

Bang rate of `g`:
<img width="1440" alt="BangRate-G" src="https://user-images.githubusercontent.com/47595933/54573608-3a20b200-49aa-11e9-891c-c8b38ceb7e14.png">

Bang rate of `f`:
<img width="1440" alt="BangRate-F" src="https://user-images.githubusercontent.com/47595933/54573613-40af2980-49aa-11e9-8a37-8b67c599ecc8.png">

Bang rate of `c`:
<img width="1440" alt="BangRate-C" src="https://user-images.githubusercontent.com/47595933/54573626-4c025500-49aa-11e9-9c2c-3467a56285cd.png">

Bang rate of `8`:
<img width="1440" alt="BangRate-8" src="https://user-images.githubusercontent.com/47595933/54573634-53296300-49aa-11e9-89dc-687ec2ebd00e.png">

Bang rate of `4`:
<img width="1440" alt="BangRate-4" src="https://user-images.githubusercontent.com/47595933/54573640-5f152500-49aa-11e9-954b-72da6fbe399f.png">

Bang rate of `2`:
<img width="1440" alt="BangRate-2" src="https://user-images.githubusercontent.com/47595933/54573651-689e8d00-49aa-11e9-85cb-c638cd25f94b.png">

Bang rate of `1`:
<img width="1440" alt="BangRate-1" src="https://user-images.githubusercontent.com/47595933/54573660-73592200-49aa-11e9-8855-c02f092c19df.png">

Here is also a plain `D1` with note length of `1`:
<img width="1440" alt="BangRate-D1" src="https://user-images.githubusercontent.com/47595933/54573664-7b18c680-49aa-11e9-8ba3-72dceea223be.png">

**Comment by neauoire** [comment]
I have an idea, I'll keep in memory all the notes that are pressed, and if that note already exists I will trigger a note_off automatically.

**Comment by neauoire** [comment]
Fixed :)
