### ISSUE TITLE
Unable to change program size with ctrl&meta [, ], {, and }

### ISSUE THREAD

**Issue by johannesgunnar** [hundredrabbits/Orca#7]
> ctrl/meta+] increase program size vertically.
> ctrl/meta+[ decrease program size vertically.
> ctrl/meta+} increase program size horizontally.
> ctrl/meta+{ decrease program size horizontally.

It seems that the following key combinations do not work for me on Xubuntu 18.04. Nothing simply happens. Increasing and decreasing the grid size with just [, ], { and } works fine though.

At first I thought it was because of how these symbols are written with my icelandic keyboard (alt gr+6 to 8) but I was unable to get this work even with an english keyboard.

**Comment by neauoire** [comment]
Oh no, sorry they aren't implemented yet, I've only started working on the keyboard scheme for these, you're just too fast. Give me an hour or two and it should be working :)

**Comment by neauoire** [comment]
Implemented

**Comment by johannesgunnar** [comment]
haha. terribly sorry about that.
