### ISSUE TITLE
Add Midi Clock Out

### ISSUE THREAD

**Issue by neauoire** [hundredrabbits/Orca#74]
Work started, but interrupts the midi signal.

See [this](https://github.com/hundredrabbits/Orca/blob/master/desktop/core/io/midi.js#L126).

**Comment by okyeron** [comment]
Is there a branch for the work on this so far?

**Comment by neauoire** [comment]
no but I think the clock code is still in clock.js

**Comment by okyeron** [comment]
I'm not making sense of the clock code so I'm not sure how to implement this myself yet.... but here's an idea for Clock Out:

Add a `Send MIDI Clock` option to the Clock menu. If this is `on`, then just send a stream of `this.outputDevice().send([0xF8])` at 24 ppq with the current tempo. I don't think it needs to be tied to transport control.

Then... maybe midi start/stop commands could be mapped to the spacebar start/stop function?

**Comment by okyeron** [comment]
works over here. maybe needs some more testing? 
https://github.com/okyeron/Orca-1/tree/midi-clock

**Comment by okyeron** [comment]
#167 

Close Issue?

**Comment by neauoire** [comment]
YESH! Thanks a lot that's an old one too, I've wanted this for a long time
