### ISSUE TITLE
Add button to toggle hardware acceleration

### ISSUE THREAD

**Issue by sporeball** [hundredrabbits/Orca#78]
i can't use the Window Capture or Game Capture sources in [OBS](https://obsproject.com/) to capture footage of Orca unless i build Orca from source and explicitly disable its hardware acceleration using [this](https://github.com/electron/electron/blob/master/docs/api/app.md#appdisablehardwareacceleration) method.

to get around this (and since not everyone needs to disable it in the first place) the ability to toggle hardware acceleration from within Orca would be nice. i would add it in a PR myself but Orca's codebase goes a little too far over my head 😛

**Comment by neauoire** [comment]
Hardware acceleration cannot be toggled once the application has started I think.
Sorry :/

**Comment by sporeball** [comment]
correct.
it might be sufficient to add a new variable somewhere that determines whether `app.hardwareAcceleration()` should get called at runtime or not, as well as a menu item that flips this variable and restarts the app? again, not sure

**Comment by neauoire** [comment]
If you want to try to make this process better, you could add a variable stdin, and in main.js add a function that toggles HA. I'd merge that :)

**Comment by sporeball** [comment]
i'm still having trouble thinking through how exactly i should implement this.
could you clarify what you mean by stdin?

**Comment by neauoire** [comment]
You can pass parameters [from the console](https://stackoverflow.com/questions/30815446/how-to-pass-command-line-argument-in-electron), so you might want to do something like adding a parameter in the build script that turns of HA.

**Comment by sporeball** [comment]
why not use localStorage to keep track of it, like the theme system does?

**Comment by neauoire** [comment]
Sure, give it a shot :)

**Comment by sporeball** [comment]
this took me a few days and ***is not ready to be merged yet***, but i [just pushed a new commit](https://github.com/sporeball/Orca/commit/8f147252981fa7ad08f7ea4762eae1789d6ebf6f) to my fork.
i was hoping it could be examined, as it throws an error during load which now admittedly has me lost again:
```
App threw an error during load
TypeError: Cannot destructure property `dialog` of 'undefined' or 'null'.
    at new Source ([Orca install directory]\desktop\sources\scripts\source.js:5:46)
    at new Data ([Orca install directory]\desktop\sources\scripts\data.js:7:17)
    at Object.<anonymous> ([Orca install directory]\desktop\main.js:7:14)
    at Object.<anonymous> ([Orca install directory]\desktop\main.js:82:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at loadApplicationPackage ([Orca install directory]\desktop\node_modules\electron\dist\resources\default_app.asar\main.js:286:12)
```

**Comment by mactkg** [comment]
@sporeball 
I took a look your commit.
`electron.remote` is module for the renderer process, but code that you commited loads and initialize `Data` at `main.js`, which is ran in main process.
https://electronjs.org/docs/api/remote

To deal with it, I think that we should initialize `Data` at `soruce/terminal.js`.
