### ISSUE TITLE
Ctrl + / Shortcut Does not Work in Linux

### ISSUE THREAD

**Issue by bcgreen24** [hundredrabbits/Orca#81]
The 'Ctrl + /' shortcut for toggling comment blocks does not work in Linux.  I'm using the latest version of Orca (pulled today, 4/15/2019).  Confirmed it works in Windows.

**Comment by neauoire** [comment]
Oh, I should use the key code instead of the key name perhaps.

**Comment by neauoire** [comment]
I'm curious, if you look in the menu, in `Edit > Block Comment`, what does it say for the shortcut?

**Comment by bcgreen24** [comment]
It says 'Ctrl + /'.

Bryan

**Comment by bcgreen24** [comment]
Fixed!
