### ISSUE TITLE
Insert mode selection problem and more.. windows 10

### ISSUE THREAD

**Issue by sense-amr** [hundredrabbits/Orca#82]
When selecting text and moving around with arrows .. text behaves not as expected..
1. moving selection with up arrow .. = diagonal movement of selection upwards direction.
2. moving selection with down arrow = diagonal movement of selection downwards direction
3. moving selection to the right .. does not move selected text..

**Comment by neauoire** [comment]
Cannot reproduce on OSX.

**Comment by sense-amr** [comment]
windows 10

**Comment by sense-amr** [comment]
ill make a video for you if you like

**Comment by neauoire** [comment]
@nobodycarestrue sent me a video, I can see it on other people's computers.
I'll boot on linux and see if I get this problem too :)

**Comment by neauoire** [comment]
Oh you're using the build from itch and not the `/master`!
Okay, I've pushed a build to itch that should fix this issue 👍 
Let me know if this problem is gone after updating from the Itch Client.

**Comment by sense-amr** [comment]
i was using the master that was available from your site .. 
latest master

**Comment by neauoire** [comment]
available from my site.. I'm not sure I understand.

In any case, is either the github master, or the itchio build still giving you this issue?

**Comment by sense-amr** [comment]
https://hundredrabbits.itch.io/orca/purchase?popup=1

**Comment by neauoire** [comment]
Okay that's the itch builds, and not the `/master` branch of this repo.
So you're saying that the builds are still giving you this issue.

Gotcha :) I'll investigate this further.

**Comment by sense-amr** [comment]
yeh i downloaded it via the latest available from that link above .. i didnt login to any client to do so .. not really wanting to make any logins if possible .. i just want to download the latest version as released.. of the master.. and of course there is no built exe of this available from the github .. so the only place i can get it is that link .. otherwise i could keep existing folder and manually replace cores and resources..

**Comment by sense-amr** [comment]
![image](https://user-images.githubusercontent.com/1504019/56282877-8733a780-6153-11e9-8cb7-dce22aeac94d.png)

no exe is available from the github .. nd hence no BUILT version is available to users other than the link from the site https://hundredrabbits.itch.io/orca/purchase which is where i got this version for windows.. 
which i can only assume is updated from the nightly master build..


Several issues exist.. .. in this version.. where orca does not behave as expected..
https://www.dropbox.com/s/iz1vogmczo17ebq/orca%20problems_Trim.mp4?dl=0

1. Shown in the video .. is movement of selection .. using ONLY Alt Up / Down arrows... 
text moves diagonally.. unexpectedly ..
2. Midi output device is NOT activated ALL the time when selected.. 
3. Slow down on selection of text and cursor move.. still present..

**Comment by sense-amr** [comment]
Also incidentally as far as i can tell, and i have tried it .. running:..
```git clone https://github.com/hundredrabbits/Orca.git
cd Orca/desktop/
npm install
npm start```

does NOT create an executable file.. 
it does allow a person to run orca from the shell tho .. 
but they will have to perform this npm build every time they want to run orca that way...
It is not as a user would expect a prebuilt *exe.. for orca.. which can just be run .. easily

**Comment by neauoire** [comment]
Let's have a look, so, in the video, I see that drag glitch in insert mode, that looks like an old build since the bottom left position color does not highlight, this was fixed [here](https://github.com/hundredrabbits/Orca/commit/0e3cff87dcc7e346490666cb395229020b1a1684), so I'm guessing this might be an older build? I'm not sure why you ended up with this build, I have a feeling that Itch might have had an issue with their cache or something.

**Comment by sense-amr** [comment]
no running "latest" git of orca does NOT replicate the same issue with regard to the Alt move of text.. 
however the other issues mentioned here do remain

**Comment by sense-amr** [comment]
i also noticed the lack of the control + space in order to select existing midi outputs..

**Comment by neauoire** [comment]
Ah! Amazing :) Thank you so much for your patience to help me debug this cursor thing!

**Comment by sense-amr** [comment]
i dunno whats up with the Itch repo of "builds" not updating to the latest .. i cant know how that works or why .. but i do know many people will be getting orca from there.. and those who run windows will be encountering these problems i mentioned above ..

**Comment by neauoire** [comment]
I'm curious, this is not related to the cursor issue, but in `2)`, the midi selection bug. Does it give you any warning or error in the console?

**Comment by neauoire** [comment]
I'll double check with itch to make sure that the cache has been cleared 👍

**Comment by sense-amr** [comment]
yeh it does.. 
Midi Input Device: UC Midi Port 1
C:\Users\Adam Raisbe…core\io\midi.js:142 Midi Output Device: loopMIDI Port
C:\Users\Adam Raisbe…core\io\midi.js:142 Midi Output Device: UC Midi Port 1
C:\Users\Adam Raisbe…core\io\midi.js:153 Midi Input Device: loopMIDI Port
﻿

​
but the thing is its just not updating the selection either visually or functionally.. untill after the second press.. even tho it shows in the console that it has

**Comment by neauoire** [comment]
Dang, I was hoping for a big red error or something.
I'm not sure why this is messing up, I'll try to poke around at this.

**Comment by sense-amr** [comment]
also another STRANGE thing i just noticed.. 
I just changed the tempo in my DAW.. with of course no indication other than the set bpm in orca to tell me that the DAW and ORCA were currently connected..

and i noticed that it slides the tempo down? .. incidentally i went from a DAW tempo of 110 to 20. orca is now at 60 or so by the sounds of it .. definitely not 20

**Comment by neauoire** [comment]
the orca bpm caps down at 60, and up at 300.

**Comment by neauoire** [comment]
yeah there's an issue with the bpm at the moment. 
It's a bit tricky to fix, but it's a top of my list.

**Comment by sense-amr** [comment]
maybe this helps ?

Midi Input Device: UC Midi Port 1
C:\Users\Adam Raisbe…core\io\midi.js:142 Midi Output Device: loopMIDI Port
C:\Users\Adam Raisbe…core\io\midi.js:142 Midi Output Device: UC Midi Port 1
C:\Users\Adam Raisbe…core\io\midi.js:153 Midi Input Device: loopMIDI Port
C:\Users\Adam Raisbe…scripts\clock.js:48 Clock Play
C:\Users\Adam Raisbe…core\io\midi.js:142 Midi Output Device: loopMIDI Port


​

**Comment by neauoire** [comment]
these looks good, if it was red, then it wouldn't indicate that orca is having trouble understanding a command. It's hard for me to test this one, because I only have 2 midi outputs to test, I'm trying to see if I can get 2-3 extra virtual instruments so I have more to choose from. This issue doesn't seem to happen with just 2 instruments.

**Comment by sense-amr** [comment]
no they do just seem like warnings or logs of whats going on .. there isnt any specific errors i can find in any of the console logs ..

**Comment by sense-amr** [comment]
Clock Play
C:\Users\Adam Raisbe…scripts\clock.js:55 Clock Stop
C:\Users\Adam Raisbe…core\io\midi.js:153 Midi Input Device: UC Midi Port 1
C:\Users\Adam Raisbe…scripts\clock.js:48 Clock Play
C:\Users\Adam Raisbe…scripts\clock.js:55 Clock Stop
C:\Users\Adam Raisbe…core\io\midi.js:142 Midi Output Device: UC Midi Port 1
C:\Users\Adam Raisbe…scripts\clock.js:48 Clock Play
C:\Users\Adam Raisbe…scripts\clock.js:55 Clock Stop
C:\Users\Adam Raisbe…core\io\midi.js:153 Midi Input Device: loopMIDI Port
C:\Users\Adam Raisbe…scripts\clock.js:48 Clock Play
C:\Users\Adam Raisbe…scripts\clock.js:55 Clock Stop
C:\Users\Adam Raisbe…scripts\clock.js:48 Clock Play
C:\Users\Adam Raisbe…scripts\clock.js:55 Clock Stop
C:\Users\Adam Raisbe…core\io\midi.js:142 Midi Output Device: loopMIDI Port
C:\Users\Adam Raisbe…scripts\clock.js:48 Clock Play
C:\Users\Adam Raisbe…scripts\clock.js:55 Clock Stop

it only played after the second selection here..
