### ISSUE TITLE
Random doesn't allow upper case letters

### ISSUE THREAD

**Issue by hizzvizz** [hundredrabbits/Orca#83]
I wanted to loop through random letters between A and G, but it made all the upper case letters lower and thus plays flat versions of the notes I want.

![image](https://user-images.githubusercontent.com/4871529/56300389-e23dae00-6103-11e9-9e28-3cd2e69ea5dd.png)

**Comment by neauoire** [comment]
It should now work with all logic operators(`A`, `I`, `M`, `R` and even `C`).

**Comment by neauoire** [comment]
```
R(A,H) = [A,B,C,D,E,F,G]
R(a,h) = [a,b,c,d,e,f,g]
R(a,H) = [a,b,c,d,e,f,g]
```
