### ISSUE TITLE
Pixelated zoom

### ISSUE THREAD

**Issue by mashaal** [hundredrabbits/Orca#86]
When adjusting zoom level, the canvas renderer becomes quite pixelated. Here is a screenshot of 8x.

![Screen Shot 2019-04-21 at 7 12 46 am](https://user-images.githubusercontent.com/6100364/56462353-7c07a280-6405-11e9-9992-df97856ade6f.png)

I believe this happens when using the native webFrame zoom and `fillText` together. [https://stackoverflow.com/a/21123769](https://stackoverflow.com/a/21123769)

Environment:
Current Orca: 045566bf9d1f95c8e2c2064758f5196f4103757b
MacOSx with external monitor (4k)

**Comment by neauoire** [comment]
That #87 fix feels pretty solid to me.
