### ISSUE TITLE
Certain base36 number literals being parsed as instructions

### ISSUE THREAD

**Issue by elyatai** [hundredrabbits/Orca#9]
For example, when trying to use the `T` instruction with a length of 16 (`g`), the `g` is being parsed as the instruction instead, causing all the values originally locked inside the track to start executing on their own as well. However, this doesn't happen when creating the `g` using an `A`dd instruction on the line above.

Example code:
```
0gTCDEFGHIJKLMNOPQR
...................
```

**Comment by neauoire** [comment]
If you are using the builds from Itch.io, I just pushed a new version where the lowercase `g` doesn't override passive mode. If you're working from the repo, just pull again :) 
Let me know if that works for you.

<img width="688" alt="screen shot 2018-12-14 at 12 02 50 pm" src="https://user-images.githubusercontent.com/1455726/49974980-325f0500-ff98-11e8-893a-d877e675b6ed.png">

**Comment by elyatai** [comment]
ah okay, thanks!
