### ISSUE TITLE
Implement MidiCC discrete & continuous modes

### ISSUE THREAD

**Issue by neauoire** [hundredrabbits/Orca#92]
http://manual.ardour.org/working-with-midi/

**Comment by 2019paper** [comment]
For me, controllers work by checking `Edit > Preferences > Control Surfaces > Generic MIDI > Show Protocol Settings > Motorised` in Ardour

**Comment by 00sapo** [comment]
For me, controllers work by checking `Edit > Preferences > Control Surfaces > Generic MIDI > Show Protocol Settings > Motorised` in Ardour

**Comment by neauoire** [comment]
Implemented! Here's how it works:

```
...Z8
!008.
```

**Comment by neauoire** [comment]
I spoke too soon.

**Comment by neauoire** [comment]
I cannot implement this, I suggest using a 3rd party application to soften the curve.
