### ISSUE TITLE
Small problem with installing program

### ISSUE THREAD

**Issue by emzee831** [hundredrabbits/Orca#94]
Sorry to bother you but this is not a bug. I just have a question on how to install orca after I have downloaded the zip from the ich.io site. I am on a raspberry pi and am very new to this world.
Thank you in advance

**Comment by neauoire** [comment]
There are not arm builds on itch.io, you need to build [Orca-c](http://github.com/hundredrabbits/Orca-c). Getting Orca running on Raspberry is the hardest of all platforms. If you don't know how to use compiling tools like `gcc` I won't be able to help you. I will try to write a guide in the next couple of days.
