### ISSUE TITLE
unable to run npm start on Arch.

### ISSUE THREAD

**Issue by rdtor** [hundredrabbits/Orca#97]
> electron .

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Orca@0.1.0 start: `electron .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Orca@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-05T11_27_51_694Z-debug.log

**Comment by neauoire** [comment]
you need to cd into desktop

**Comment by rdtor** [comment]
It was run inside the desktop

**Comment by SerialForBreakfast** [comment]
I had this same problem on mac.  npm start gave the same error where 'electron .' worked just fine.

**Comment by neauoire** [comment]
The itch build is giving you this error?

**Comment by neauoire** [comment]
Are you launching it through the client?
