### ISSUE TITLE
Question: what is the D-rate for?

### ISSUE THREAD

**Issue by ondras** [hundredrabbits/Orca#99]
Please, what is the left operand for `D` used for? Is it just to multiply the D-rate value?

These seem to be identical:

```
2D4...1D8...4D2
```

**Comment by neauoire** [comment]
Yeah both numbers are multiplied and used as divider to the clock, it's usually used to sync up with C. 
See this [example](https://github.com/hundredrabbits/Orca/blob/master/examples/misc/timing.orca).
